### ISSUE TITLE
File bin/console non viene creato; errore nell'esecuzione di composer install

### ISSUE THREAD

**Issue by MatteoGheza** [trinko/giuaschool#11]
Volevo realizzare un sistema CI/CD (su Github Action) in un fork personale del progetto,
ma all'esecuzione di `composer install --no-progress --no-suggest` viene riportato il seguente errore:
`...`
`  - Installing symfony/test-pack (v1.0.6): Loading from cache`
`  - Installing symfony/web-server-bundle (v4.3.3): Loading from cache`
`Generating autoload files`
`ocramius/package-versions: Generating version class...`
`ocramius/package-versions: ...done generating version class`
`Executing script cache:clear [KO]`
` [KO]`
`Script cache:clear returned with error code 1`
`!!  Could not open input file: ./bin/console`
`!! `
`Script @auto-scripts was called via post-install-cmd`
`##[error]Process completed with exit code 1.`

L'installazione viene eseguita in un container ubuntu 18.04 su Github Action.
E' possibile visualizzare l'output completo dell'esecuzione [nella pagina Github Action dei mio fork](https://github.com/MatteoGheza/giuaschool/runs/750228849).
E' possibile visualizzare l'elenco dei comandi eseguiti [nel file php.yml](https://github.com/allerta-vvf/allerta-vvf/blob/master/.github/workflows/php.yml).

Ho provato ad eseguire gli stessi passaggi anche da un computer che uso per sviluppare webapp Symfony, con cli versione v4.16.3, php 7.4.5 e composer 1.8.0.
Seguendo README.md, non ho trovato ulteriori informazioni relative all'installazione.
Una volta risolti i problemi con Github Action, sarà possibile controllare la compilazione ad ogni commit/pull-request.
Sarà inoltre possibile realizzare un container docker per l'installazione rapida.

**Comment by trinko** [comment]
Mi pare di capire che il problema sia la mancanza dei file all'interno della directory "./bin/"
Ero convinto che venissero generati automaticamente durante l'installazione con il composer, ma rivedendo la procedura di prima installazione capisco che non è così (anche se non mi è chiara la ragione). 

L'installazione iniziale prevede di generare lo script "symfony" che poi si usa per la creazione dei file di progetto: questo crea anche i file all'interno della directory "./bin".

La soluzione dovrebbe essere aggiungere a gitHub anche i file all'interno di "./bin" visto che non vengono creati in automatico dal composer.
Li aggiungerò col prossimo commit.

**Comment by trinko** [comment]
File aggiunti con il commit 8326266eb500635187e78c0dacb49f273117ce62

Fammi sapere se ha risolto il problema.

**Comment by MatteoGheza** [comment]
Ora dovrebbe funzionare, adesso devo soltanto creare il file `.env` e configurare il database

`  - Installing symfony/test-pack (v1.0.6): Loading from cache`
`  - Installing symfony/web-server-bundle (v4.3.3): Loading from cache`
`Generating autoload files`
`ocramius/package-versions: Generating version class...`
`ocramius/package-versions: ...done generating version class`
`Executing script cache:clear [KO]`
` [KO]`
`Script cache:clear returned with error code 1`
`!!  `
`!!  In EnvVarProcessor.php line 131:`
`!!  `                                                    
`!!    Environment variable not found: "DATABASE_HOST".  `
`!!   `                                                   
`!!  `
`!!  `
`Script @auto-scripts was called via post-install-cmd`
`##[error]Process completed with exit code 1.`

**Comment by MatteoGheza** [comment]
Aggiornamento: dopo aver aggiunto gli env richiesti, indicando i dati del database, continuavo a ottenere errori che si riferivano a bug interni di Doctrine e Symfony (trovato informazioni su Github e StackOverflow). Per questo motivo, ho dovuto [rimuovere dal file composer.json](https://github.com/MatteoGheza/giuaschool/blob/MatteoGheza-patch-GithubAction/composer.json) le indicazioni che eseguivano gli script (post-install e post-update richiamavano clear:cache e altri script), in questo modo sono riuscito ad eseguire l'installazione.
Ho poi eseguito i comandi per popolare il database, ma continuo a ricevere l'errore 2006: MySQL server has gone away.
Ho controllato più volte l'installazione di MySQL, e ho provato ad utilizzarla per eseguire WordPress e il progetto demo di Symfony, senza però visualizzare il messaggio di errore.

**Comment by trinko** [comment]
Potrebbe essere un problema di aggiornamento del file dei dati iniziali "AppFixtures.php"
L'ho aggiornato con l'ultimo commit:

9e5f95310cb547d52c352c9db07ea5483b1ada91

**Comment by MatteoGheza** [comment]
Nel tempo libero, ho provato ancora molte volte ad installare giuaschool. Continuo a ricevere errori riguardanti il database durante l'installazione, anche se in un'altro db sulla stessa installazione di MySql sono riuscito ad installare un paio di software basati su Symfony e Doctrine. Nei prossimi giorni vorrei provare a realizzare un nuovo progetto in Symfony (con `symfony new my_project_name --full`), per poi confrontarlo con giuaschool, in modo da trovare le differenze nei file creati automaticamente da Symfony.

**Comment by MatteoGheza** [comment]
@trinko #12 e #13 dovrebbero correggere questi problemi. Chiuderò questa segnalazione quando le pull request saranno approvate.
