### ISSUE TITLE
Nuovo problema studenti

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#110]
Buongiorno,ho provato ad importare i docenti e alunni  compilando anche i campi non obbligatori  rispettando le stesse intestazioni nel formato csv , ma quando carico il tutto e clicco su conferma 
mi da il seguente messaggio 
ERRORE I campi di intestazione del file non corrispondono a quanto previsto.

**Comment by sempliciniluigi89** [comment]
ex.dati importati docenti https://github.com/trinko/giuaschool/files/7831798/docenti.csv

**Comment by trinko** [comment]
I file CSV devono avere le intestazioni di tutti i campi, ma puoi lasciare vuoti i dati non obbligatori.
Inoltre il separatore dei campi deve essere la virgola.
Allego due file di esempio con i soli dati obbligatori. Puoi modificarli usando Excel o LibreOffice, ma quando li salvi in formato CSV devi fare attenzione a impostare la virgola come separatore.

[IMPORTA_DOCENTI.csv](https://github.com/trinko/giuaschool/files/7833130/IMPORTA_DOCENTI.csv)
[IMPORTA_ALUNNI_GENITORI.csv](https://github.com/trinko/giuaschool/files/7833131/IMPORTA_ALUNNI_GENITORI.csv)

**Comment by sempliciniluigi89** [comment]
Qualcuno mi potrebbe rispondere?

**Comment by trinko** [comment]
Appena risposto

**Comment by sempliciniluigi89** [comment]
Il tutto si concentra in una cella separata da numerose virgole ,giusto?

**Comment by trinko** [comment]
No, quando leggi il file devi impostare la virgola come separatore, così Excel o Libreffice li separa nelle celle previste

**Comment by sempliciniluigi89** [comment]
Buonasera sono riuscito ad importare il file csv docenti adeguandolo al modello da lei mandato ,solo che non capisco perché non sta accettando il file csv degli alunni ,allego e se è possibile me lo sistemi lei ,sono dati fittizi 

https://github.com/trinko/giuaschool/files/7841355/IMPORTA_ALUNNI_GENITORI.2.csv

**Comment by sempliciniluigi89** [comment]
Pensavo fosse per il codice fiscale uguale per tutti,l'ho cambiato a ciascun studente ,ma il problema si ripete sempre

**Comment by sempliciniluigi89** [comment]
Stessa cosa con la data,ho provato a cambiare anche questa,ma niente da fare

**Comment by trinko** [comment]
Gli errori sono i seguenti:
- il codice fiscale deve essere diverso per ciascun alunno (come avevi già detto)
- sono presenti dei caratteri indecifrabili; si tratta di lettere accentate nei nomi (ad es. **Nicolò**) che dopo il salvataggio sono state trasformate in caratteri illeggibili.

Per evitare il problema delle lettere accentate, o le converti tutte con gli apostrofi (ad es. **Nicolo'**, come ho fatto nel file allegato), oppure devi salvare il documento in formato UTF-8, cosa che non sempre viene gestita bene da Excel o LibreOffice.

In linea di massima, se dopo aver modificato e salvato il file, lo riapri con un editor di testi (ad es. il blocco note) e vedi correttamente la lettera accentata, dovrebbere essere tutto ok. 

[IMPORTA_ALUNNI_GENITORI.3.csv](https://github.com/trinko/giuaschool/files/7844873/IMPORTA_ALUNNI_GENITORI.3.csv)

**Comment by sempliciniluigi89** [comment]
Buonasera,non appena carico il file csv degli alunni  da voi inviato,prima di tutto non mi carica tutti gli alunni e secondo mi rilascia questa schermata (allego file immagine)

https://user-images.githubusercontent.com/93823125/148993660-5086c903-1588-4f4c-91cd-4aed62d71104.JPG

**Comment by sempliciniluigi89** [comment]
Ho capito,non accetta una quantità elevata di studenti ,devo importare più volte.

**Comment by trinko** [comment]
Si, il tempo massimo per l'esecuzione della procedura dipende dalle impostazioni del server di hosting.

Ma, come hai visto, si risolve rifacendo più volte l'importazione e selezionando l'opzione  **SOLO NUOVI** per non avere problemi.

**Comment by sempliciniluigi89** [comment]
infatti

**Comment by sempliciniluigi89** [comment]
Buongiorno ,volevo solo sapere come fa a far avere ad ogni studente codice fiscale differente dal momento che io ho creato il tutto con excel con la funzione (fx) concatena che poi mi ritrovavo con il codice fiscale uguale per tutti gli studenti?

**Comment by trinko** [comment]
Se non hai i codici fiscali reali, basta inserire un numero progressivo, da 1 in poi. 
Si fa inserendo il primo valore in una cella, cliccando con il mouse sul quadratino che appare in basso a destra sul bordo della cella e poi trascinandolo verso le altre celle da modificare.

[Vedi ad esempio questo tutorial](https://www.excelpertutti.com/numero-righe-excel-numero-progressivo/)

**Comment by sempliciniluigi89** [comment]
Buonasera ,sto cercando di importare le cattedre mediante il file csv ,ma con scarsi risultati in quanto mi dice che c'è qualcosa di sbagliato che però non capisco.Purtroppo non ci so fare con excel,questo è il problema,potrebbe vedere lei e sistemare cortesemente ciò che andava male ed evidenziarmi l'errore ?Grazie ,allego file . Se avesse il bisogni di sapere il nome del corso è il seguente : LICEO LINGUISTICO (LL)
https://github.com/trinko/giuaschool/files/7873727/CATTEDRE.csv

**Comment by sempliciniluigi89** [comment]
É urgente

**Comment by trinko** [comment]
Gli errori nel file sono i seguenti:

- il file usa il punto e virgola come separatore anziché la virgola;
- i nomi delle classi devono essere inseriti come  **1A** non **1ª A**
- sono presenti caratteri strani nei nomi
- le username di alcuni docenti contengono spazi (le username e le email non possono contenere spazi)

Riporto in allegato il file corretto.
[CATTEDRE2.csv](https://github.com/trinko/giuaschool/files/7875766/CATTEDRE2.csv)

**Comment by sempliciniluigi89** [comment]
Buonasera,purtroppo quando importo il file csv mi restituisce il seguente messaggio:ERRORE Il docente indicato nel record 1 non è presente nel sistema. Mi sembra strano , in quanto ho controllato e il docente indicato nel record 1 risulta a tutti gli effetti nel registro.

**Comment by sempliciniluigi89** [comment]
Ora ho capito l'errore, ma non saprei come e dove mettere mani.Mi dava quel messaggio di errore in quanto il registro come nome utente del docente mette prima il nome e poi il cognome ,mentre qui ,nel file da lei ricevuto ,sta prima il cognome e poi il nome.Potrebbe per favore provvedere alla sistemazione?Grazie

**Comment by trinko** [comment]
Questo è il file di importazione corretto:
[CATTEDRE3.csv](https://github.com/trinko/giuaschool/files/7877502/CATTEDRE3.csv)

**Comment by sempliciniluigi89** [comment]
Grazie mille ,c'è solo un problema: arriva a caricare fino al docente 194 e poi non precede più fino al 274

**Comment by sempliciniluigi89** [comment]
Come mai?

**Comment by sempliciniluigi89** [comment]
Anche il file csv dei docenti  prende fino al docente 194 ,anche se provo poco alla volta
https://github.com/trinko/giuaschool/files/7877628/Cartel1.3.csv

**Comment by sempliciniluigi89** [comment]
Spero in una viva risposta

**Comment by trinko** [comment]
In entrambi i file il docente è lo stesso: ha nel nome una lettera accentata "Nicolò Sabattini".
Il problema è sempre quello, nei file che hai caricato c'è un problema di conversione delle lettere accentate.

Nel file delle cattedre, avevo corretto il problema, e il docente viene indicato con la username **nicol.sabattini**, che probabilmente non è una username esistente. Questo lo puoi anche risolvere modificando, come amministratore, la username del docente.

In generale, nei file di importazione, o elimini le lettere accentate sostituendole con apostrofi (es. Nicolo') oppure devi assicurarti che vengano scritte correttamente dopo che hai salvato il file.
