### ISSUE TITLE
Installazione non andata a buon fine

### ISSUE THREAD

**Issue by gherardiangelo1969** [trinko/giuaschool#111]
Buongiorno, sono un nuovo utente .Sono qui perché ho sentito diverse persone parlare del progetto Giuaschool e così ho provato con l'ultima versione release da voi rilasciata.Premetto che io ho sempre usato Altervista e filezilla ,motivo per cui ho effettuato in filezilla l'upload della cartella giuaschool ,dopodiché ho modificato il file env inserendo i dati del mio database ed in fine , mi sono recato sul browser dove ho riportato il nome del server più la seguente stringa /install/index.php , ma il messaggio che po ricevo quando avvio la ricerca è il seguente 

alterVista
Page not found (error 404)
The page http://www.registroscuola20192020.altervista.org/install/index.php was not found on this server.
This can be due to:

The page no longer exists.
The link you have followed is not valid.
The page has been moved.
Pay attetion to UPPER and LOWER cases
http://site.altervista.org/Page.html is different from http://site.altervista.org/page.html

**Comment by trinko** [comment]
Penso che su Altervista devi usare il percorso che comprende anche la cartella public, del tipo:
**nomesito/public/install/index.php**

**Comment by sempliciniluigi89** [comment]
L'errore purtroppo è sempre lo stesso

**Comment by sempliciniluigi89** [comment]
C'è qualcuno a cui potrei far vedere il file env ?Forse ho sbagliato qualcosa lì dentro,non lo so

**Comment by gherardiangelo1969** [comment]
Mi sono rivolto all'ex.collega Semplicini Luigi , ma il problema è sempre
lo stesso

Il giorno sab 8 gen 2022 alle ore 13:11 sempliciniluigi89 <
***@***.***> ha scritto:

**Comment by gherardiangelo1969** [comment]
Come posso fare?

**Comment by trinko** [comment]
Non conosco bene Altervista per poterti aiutare. Ma sicuramente dipende dalle impostazioni di Altervista, o dai permessi di lettura su cartelle e file, o ancora dalla posizione dove hai estratto i file.

**Comment by manuelbarberi** [comment]
Ti aiuto io, manda id e pass di altervista e te lo installo io

**Comment by manuelbarberi** [comment]
sulla mia mail : manuelbarberi.mb@libero.it

**Comment by gherardiangelo1969** [comment]
Le mando il tutto sull'email .Grazie mille

**Comment by manuelbarberi** [comment]
Di nulla

**Comment by gherardiangelo1969** [comment]
Inviato

**Comment by manuelbarberi** [comment]
Arrivato

**Comment by manuelbarberi** [comment]
Procedo ad installare... Che password metto per l'admin.... comunicamela sulla mail

**Comment by gherardiangelo1969** [comment]
admin,tanto poi la cambio

Il giorno sab 8 gen 2022 alle ore 18:11 Manu ***@***.***> ha
scritto:

**Comment by manuelbarberi** [comment]
ok

**Comment by manuelbarberi** [comment]
Tra qualche ora dovrei riuscire ad installare tutto perchè ho aggiornato innoDB e adesso mi fa aggiornare il database tra qualche ora

**Comment by gherardiangelo1969** [comment]
Grazie infinite

Il giorno sab 8 gen 2022 alle ore 18:20 Manu ***@***.***> ha
scritto:

**Comment by manuelbarberi** [comment]
Entro quando ti serve?

**Comment by gherardiangelo1969** [comment]
Stasera,se è possibile

Il giorno sab 8 gen 2022 alle ore 18:22 Manu ***@***.***> ha
scritto:

**Comment by manuelbarberi** [comment]
Ok, vediamo quanto ci mette altervista ad installare il database Inno

**Comment by manuelbarberi** [comment]
Installazione terminata ... Nome utente : admin Password : 12345678

**Comment by manuelbarberi** [comment]
https://registroscuola20192020.altervista.org/relasegiua/public/login/form/

**Comment by scuolagioco** [comment]
> 
Salve, potrebbe aiutare anche me a installare il registro? Anche io ho sempre usato Altervista e FileZilla. Quindi devo importare la cartella Giuaschool su FileZilla dopodiché non so come fare, mi potrebbe aiutare lei?

**Comment by manuelbarberi** [comment]
> Buon pomeriggio, posso richiedere un aiuto con l'installazione del registro al sig. @manuelbarberi, credo che lei sia molto più esperto di me

certo
