### ISSUE TITLE
Cancellazione cartella /install

### ISSUE THREAD

**Issue by rodolfo024** [trinko/giuaschool#112]
Non succedere niente se si elimina la cartella install dopo aver fatto l'installazione giusto?

**Comment by trinko** [comment]
No, si può cancellare senza problemi.
Consiglio però di non cancellare il file **public/install/clean.txt**, che può servire per ripulire la cache nel caso si faccia qualche personizzazione. 

Infatti, dopo ogni modifica ai file (soprattutto per i template) è di norma necessario ripulire la cache, altrimenti le modifiche non saranno visibili. 
Per ripulire la cache, si rinomina il file indicato con l'estensione **.php** e lo si esegue. Al termine lo si rinomina nuovamente in **.txt**, in modo che non possa essere eseguito.
