### ISSUE TITLE
PROBLEMA

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#113]
Buongiorno, nella nuova versione, quando la segreteria va a stampare la password o comunque il docente va a stampare le note disciplinari, esce direttamente l'anno scolastico senza nessuna testata , mentre nella versione precedente usciva la testata con lo stemma italiano e con la scritta scuola superiore etc.

**Comment by trinko** [comment]
Nella nuova versione tutti i documenti generati hanno come intestazione un' immagine che deve essere personalizzata.

L'immagine da personalizzare è **public/img/intestazione-documenti.jpg**. Consiglio di mantenere le stesse dimensioni dell'immagine originale, quindi inserire una foto (o scansione) dell'intestazione del proprio istituto.

Una volta caricata la nuova immagine, è necessario ripulire la cache:
- rinominare il file **public/install/clean.txt** con l'estensione **.php** 
- eseguirlo inserendo l'indirizzo del tipo `http://nome_sito/install/clean.php` sul proprio browser
- al termine dell'esecuzione, rinominare il file nuovamente con l'estensione **.txt**, in modo che non possa essere eseguito da altri
