### ISSUE TITLE
Nuovo aggiornamento: richiesta informazioni 

### ISSUE THREAD

**Issue by Lucaccc** [trinko/giuaschool#115]
Buongiorno, volevo sapere quali fossero le novità apportate con l’ultimo aggiornamento, in modo da valutare se farlo con celerità o attendere il primo momento utile…
Grazie mille.

**Comment by trinko** [comment]
Le modifiche riguardano essenzialmente:
- correzioni di vari errori minori
- aggiunta del menu SCUOLA per la configurazione da parte dell'amministratore
- aggiunta della procedura di installazione

i dettagli sono [qui](https://github.com/trinko/giuaschool/releases/tag/v1.4.2)

**Comment by Lucaccc** [comment]
> Le modifiche riguardano essenzialmente:
> 
> * correzioni di vari errori minori
> * aggiunta del menu SCUOLA per la configurazione da parte dell'amministratore
> * aggiunta della procedura di installazione
> 
> i dettagli sono [qui](https://github.com/trinko/giuaschool/releases/tag/v1.4.2)

Grazie mille.
