### ISSUE TITLE
Errore grave

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#119]
Buongiorno ,ogni volta che accedo come dsga ,tecnico ,amministratore e mi dirigo nella sezione bacheca mi esce il seguente messaggio qui allegato 

https://user-images.githubusercontent.com/93823125/149427769-51c96037-16de-4a3d-86c6-2b9a7dabf426.png

**Comment by trinko** [comment]
Non è un errore, ma solo un avviso (warning).
Il problema è che stai utilizzando il registro con l'ambiente di sviluppo (DEV) e questo fa sì che si blocchi per segnalare anche gli avvisi.

Modifica nel file **.env** l'ambiente da utilizzare impostando quello di produzione, modificando la riga seguente:

`APP_ENV=prod
`
