### ISSUE TITLE
Accesso negato

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#120]
Buongiorno ,quando provo ad entrare mediante alias come preside inserendo il nome utente della stessa preside mi dice : Utente sconosciuto ,non so il perché eppure nel menu scuola , nell'area dirigente il nome utente è quello

**Comment by gmontalbano5ct** [comment]
non la so aiutare....  mi può aiutare con il mio problema per favore ?#116

**Comment by trinko** [comment]
> Buongiorno ,quando provo ad entrare mediante alias come preside inserendo il nome utente della stessa preside mi dice : Utente sconosciuto ,non so il perché eppure nel menu scuola , nell'area dirigente il nome utente è quello

Probabilmente è un problema di password.

Prova, da amministratore, ad usare la funzione alias (**SISTEMA > ALIAS**) per entrare con lo stesso utente.
Se riesci ad entrare, allora il problema era la password. 
Prova ad impostare una nuova password, sempre da amministratore (**SISTEMA > PASSWORD**) e riprova ad eseguire il login.
