### ISSUE TITLE
Installazione registro con Altervista

### ISSUE THREAD

**Issue by scuolagioco** [trinko/giuaschool#121]
Buon pomeriggio. Ho letto dalle precedenti Issues che il sig. @manuelbarberi offre il suo aiuto ad alcune persone per l’installazione del registro. Essendo che sono ignorante in questo campo e vorrei installare il registro per il mio Istituto, potrebbe aiutare anche me? Ho provato anche a scriverle via mail ma senza alcuna risposta 😅

**Comment by gmontalbano5ct** [comment]
infatti io pure ho bisogno di aiuto  ho provato pure ad inviargli un email😅

**Comment by manuelbarberi** [comment]
Scusate l’assenza, inoltrare sulla mia mail tutti i dettagli e vi aiuto

**Comment by scuolagioco** [comment]
> 

Le ho inviato una mail, riesce a rispondermi 😂
