### ISSUE TITLE
Errore modalità voto 

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#123]
Buonasera, vorrei sapere e  capire il perché quando ad esempio in caso del voto di un test d'ingresso, dunque una valutazione multipla quando si clicca non considerare nella media,automaticamente parte l'opzione che non permette ai genitori di visualizzare il voto

**Comment by trinko** [comment]
E' il contrario.

Cioè, per ogni tipo di valutazione (singola o multipla), se si sceglie di rendere NON VISIBILE il voto, automaticamente viene anche escluso dalla media (perché non è stato comunicato).

Ma se scegli di togliere un voto dalla media, questo può essere visibile per i genitori (a scelta del docente).
