### ISSUE TITLE
Valutazione Religione 

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#128]
Buongiorno,la norma ministeriale ci obbliga a mettere per la cattedra di religione sia alle verifiche scritte/pratiche che interrogazioni orali la valutazione non numerica bensì giudizio, cosa che giuaschool ancora non usa ,o meglio usa solo in pagella.

**Comment by trinko** [comment]
Si può usare la valutazione con giudizi in qualsiasi materia.
Basta lasciare non definito il voto numerico e scrivere il giudizio nell'apposito campo GIUDIZIO.

**Comment by sempliciniluigi89** [comment]
Sì, ma così non ha valore una volta che si arriva in sede di scrutinio

Il Mer 19 Gen 2022, 15:18 Antonello Dessì ***@***.***> ha
scritto:

**Comment by trinko** [comment]
Guarda che non c'è nessun problema.
Quando si arriva allo scrutinio si usa la proposta di voto, che inserisce il docente di religione, e che è previsto che sia in giudizi.

Inoltre, nell'inserire la proposta di voto (prima dello scrutinio) il docente può vedere il dettaglio delle valutazioni, che riporta tutte le valutazioni, che siano numeriche o giudizi. 
Unica cosa che manca è la media, che ovviamente non può essere fatta.
