### ISSUE TITLE
problema scrutinio

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#129]
non riesco a mettere il dirigente scolastico come presidente dello scrutinio e non riesco ad accedere al utenza preside come faccio @rodolfo024

**Comment by trinko** [comment]
Devi dare più dettagli affinché si possa capire quale sia il problema.

Esattamente che messaggio di errore viene visualizzato e dopo quale operazione? Quale è il contenuto del file di log?

**Comment by gmontalbano5ct** [comment]
![Screenshot_2022-01-20-06-47-18-938_com android chrome](https://user-images.githubusercontent.com/93207960/150280964-6f1a9106-def5-481f-98a9-e7bcfc7f506c.jpg)
![Screenshot_2022-01-20-06-47-06-647_com android chrome](https://user-images.githubusercontent.com/93207960/150280973-3ee054da-a0dd-4283-844c-d5b06f6e3c17.jpg)

**Comment by rodolfo024** [comment]
Ha inserito le materie educazione civica, comportamento, supplenza, sostegno e religione, contrassegnandole specificatamente dalla maschera di inserimento? Per lo scrutinio sono fondamentali ed. Civica e comportamento, ma senza supplenza da lo stesso errore appena su vuole accedere al registro di classe.
Nell’ordinamento il comportamento deve inserire 990;
Il sostegno 999
La supplenza 0

**Comment by gmontalbano5ct** [comment]
Ok provo

**Comment by gmontalbano5ct** [comment]
Fatto @rodolfo024 il problema è che non riesco ad inserire il dirigente non me lo fa selezionare perché?

**Comment by trinko** [comment]
Hai inserito il dirigente dal menu **SCUOLA > DIRIGENTE SCOLASTICO**?

In ogni caso devi caricare il file di log, altrimenti non è possibile sapere cosa è successo: **var/log/prod_xx.log**

**Comment by gmontalbano5ct** [comment]
Come faccio @rodolfo024

**Comment by gmontalbano5ct** [comment]
Si l ho messo il dirigente

**Comment by gmontalbano5ct** [comment]
@rodolfo024 @trinko

**Comment by rodolfo024** [comment]
Posso entrare su phpmyadmin per verificare se esiste l'utenza preside anche sul database?

**Comment by gmontalbano5ct** [comment]
grazie @rodolfo024

**Comment by gmontalbano5ct** [comment]
il problema è anche che se metto delle valutazioni mi spuntano nel primo trimestre se non faccio lo scrutinio

**Comment by trinko** [comment]
Per capire cosa significa l'errore riportato bisogna che carichi il file di log:
- vai nel file manager del tuo servizio di hosting e cerca la cartella **var/log**
- al suo interno cerca il file con un nome del tipo **app_prod-XXXX.log**, dove XXXX è la data in cui hai visto l'errore; se non sei sicuro, vai nel registro, riesegui la procedura sino a generare nuovamente l'errore, quindi prendi il file di log con la data di oggi;
- a questo punto puoi scaricare sul tuo computer il file di log e allegarlo qui ad un messaggio.

**Comment by gmontalbano5ct** [comment]
Ho risolto grazie per l aiuto
