### ISSUE TITLE
Il filtro della data nelle circolari non funziona

### ISSUE THREAD

**Issue by Franck1421** [trinko/giuaschool#130]
Salve,
se si prova, sia da studente che da genitore, ad utilizzare il filtro della data nelle circolari il registro mostrerà sempre che non ci sono risultati.

**Comment by trinko** [comment]
Non è che oltre al filtro data hai lasciato impostato anche un altro filtro (es. DA LEGGERE)? I filtri vengono combinati assieme per la ricerca.

Se non è così, dovresti indicare i passi per riprodurre il problema, del tipo:
1. inserisco e pubblico una circolare in data xx destinata a tutti (alunni,genitori, docenti, ata), possibilmente allegare screenshot dei dettagli della circolare pubblicata
2. verifico che un alunno visualizza la circolare se non c'è filtro data
3. verifico che lo stesso alunno non visualizza la circolare se il filtro data è XXX

**Comment by Franck1421** [comment]
Da genitore entrando nelle circolari senza applicare alcun filtro si può vedere:
![Desktop Screenshot 2022 01 20 - 20 22 37 13](https://user-images.githubusercontent.com/51267237/150408180-a1f6d5d9-fba7-49e8-992f-e48ccb7461a7.png)
Applicando il filtro per il mese di gennaio 2022 invece:
![Desktop Screenshot 2022 01 20 - 20 22 55 92](https://user-images.githubusercontent.com/51267237/150408383-d27860c4-d194-496a-9951-6578a275a6f6.png)

**Comment by trinko** [comment]
Sistemato
