### ISSUE TITLE
PROBLEMA APPLICAZIONE 

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#140]
Buona sera come faccio a implementare l'applicazione di giua school nel mio registro?

**Comment by gmontalbano5ct** [comment]
@rodolfo024

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by trinko** [comment]
Non è chiaro cosa intendi per "implementare nel tuo registro".

L'applicazione giua@school viene installata, in modo indipendente da altre installazioni del proprio registro.

Ti invito a leggere la [documentazione](https://trinko.github.io/giuaschool-docs/)

**Comment by gmontalbano5ct** [comment]
Ok grazie
