### ISSUE TITLE
Errore 503 durante la firma del registro

### ISSUE THREAD

**Issue by moronileonardo** [trinko/giuaschool#147]
Buonasera, da un paio di giorni sto provando il registro Giuia, per sostituire il vecchio LampSchool che viene ancora utilizzato dalla mia scuola. 
Ho riscontrato qualche problema:
Aggiungendo un alunno dal menu alunni→modifica, la tabella rimane vuota, anche se nel database risulta presente.
Inoltre, effettuando la firma del registro come docente, ottengo come risposta un errore 503, che, pare risolversi, eliminando la cartella /var/cache/prod, ma purtroppo si ri-crea automaticamente, ricreando il problema. 

Grazie mille. Spero che i problemi vengano risolti al più presto. Non esitate a contattarmi nel caso aveste bisogno di specifiche!

**Comment by trinko** [comment]
Il problema dell'alunno è dovuto sicuramente al fatto che hai utilizzato uno username per l'alunno o il generatore che non rispetta il formato standard.
Riprova ad inserire un alunno/genitore senza specificare username e non avrai problemi. Puoi anche modificare la username dell'alunno/genitore da database per visualizzare quanto già inserito.

Il formato della username degli alunni termina sempre con ".sX" dove X è un valore numerico (1 o successivi in caso di omonimia) 

Il formato della username dei genitori, indica una username identica a quella dell'alunno, ma che termina in ".fX" e ".gX", dove X è un valore numerico (1 o successivi in caso di omonimia) 


Per il secondo problema, relativo all'errore 503, devi riportare il contenuto dell'errore riportato nel file di log, altrimenti è impossibile sapere quale sia il problema. Il log si trova nei file **var/log/app_prod_XXX.log**

**Comment by moronileonardo** [comment]
> Il problema dell'alunno è dovuto sicuramente al fatto che hai utilizzato una username per l'alunno o il generatore che non rispetta il formato standard. Riprova ad inserire un alunno/genitore senza specificare username e non avrai problemi. Puoi anche modificare la username dell'alunno/genitore da database per visualizzare quanto già inserito.
> 
> Il formato della username degli alunni termina sempre con ".sX" dove X è un valore numerico (1 o successivi in caso di omonimia)
> 
> Il formato della username dei genitori, indica una username identica a quella dell'alunno, ma che termina in ".fX" e ".gX", dove X è un valore numerico (1 o successivi in caso di omonimia)
> 
> Per il secondo problema, relativo all'errore 503, devi riportare il contenuto dell'errore riportato nel file di log, altrimenti è impossibile sapere quale sia il problema. Il log si trova nei file **var/log/app_prod_XXX.log**
> 
> PS si chiama giua@school ;-)

Grazie mille della risposta! Provvedo subito a cambiare i vari username. Intanto, ecco il file di log:
[LOG](https://www.moronileonardo.net/app_prod-2022-01-29.log)

**Comment by trinko** [comment]
Sembra che ci siano problemi con la directory della cache. 
Controlla anzi tutto che la cartella **var/cache/prod** abbia i permessi di lettura/scrittura/esecuzione per l'utente del web server.
Anche le cartelle del percorso devono avere i permessi lettura/esecuzione.

Poi, per cancellare la cache, non farlo a mano: rinomina il file **public/install/clean.txt** in **clean.php**, quindi esegui dal browser http://nomesito/install/clean.php

**Comment by moronileonardo** [comment]
> Sembra che ci siano problemi con la directory della cache. Controlla anzi tutto che la cartella **var/cache/prod** abbia i permessi di lettura/scrittura/esecuzione per l'utente del web server. Anche le cartelle del percorso devono avere i permessi lettura/esecuzione.
> 
> Poi, per cancellare la cache, non farlo a mano: rinomina il file **public/install/clean.txt** in **clean.php**, quindi esegui dal browser http://nomesito/install/clean.php

I permessi sono impostati su 755, dovrebbe essere corretto. Mi chiedo da cosa possa dipendere, allora... 
In ogni caso, ringrazio nuovamente per l'aiuto che mi sta prestando!

**Comment by trinko** [comment]
> I permessi sono impostati su 755, dovrebbe essere corretto. Mi chiedo da cosa possa dipendere, allora...

Non è detto, se l'utente proprietario delle cartelle non è lo stesso del web server. 
Prova a impostarli su 777 e vedi se risolve.

Altrimenti, nel messaggio di errore del log dice che non trova un certo file: dovresti controllare se effettivamente esiste o no quel particolare file.
