### ISSUE TITLE
Problema di installazione

### ISSUE THREAD

**Issue by Faobi69** [trinko/giuaschool#15]
Salve, stò provando ad installare il progetto però non sembra funzionare, premetto che sono su windows e che ho scaricato xampp e attivato il database di xampp e anche apache. ho scaricato e copiato la cartella giuaschool contenente tutti i file del progetto che ho messo su <percorso_installazione_xampp>\xampp\htdocs\
ho cercato su <percorso_installazione_xampp>\xampp\php\php.ini la stringa ;extension=php_intl.dll ma sembra non esserci o meglio c'è qualcosa di simile ma non uguale;
ho eseguito questi comandi: 
<percorso_installazione_xampp>\xampp\php\php bin\console doctrine:database:create
<percorso_installazione_xampp>\xampp\php\php bin\console doctrine:schema:create
tramite il prompt dei comandi di windows ma come risposta ottengo:
Could not open input file: bin\symfony_requirements
quindi non sò che altro fare per provare questo progetto, qualche consiglio?

**Comment by Faobi69** [comment]
C:\Users\fabio>cd C:\xampp\htdocs\giuaschool

C:\xampp\htdocs\giuaschool>C:\xampp\php\php bin\symfony_requirements
Could not open input file: bin\symfony_requirements

C:\xampp\htdocs\giuaschool>
C:\xampp\htdocs\giuaschool>

**Comment by Faobi69** [comment]
C:\xampp\htdocs\giuaschool>C:\xampp\php\php bin\console doctrine:schema:create
PHP Warning:  require(C:\xampp\htdocs\giuaschool/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\giuaschool\bin\console on line 15

Warning: require(C:\xampp\htdocs\giuaschool/vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\giuaschool\bin\console on line 15
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\giuaschool/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\giuaschool\bin\console on line 15

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\giuaschool/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\giuaschool\bin\console on line 15

**Comment by trinko** [comment]
Purtroppo non ho avuto tempo di rivedere la documentazione: ci manca la parte dell'installazione di Symfony.

1) crea una directory apposita in C:\xampp per l'installazione del Composer
  `mkdir C:\xampp\composer`

2) posizionati nella directory:
  `cd C:\xampp\composer`

3) scarica e installa il composer nella directory corrente seguendo le indicazioni della pagina seguente:
[Download Composer](https://getcomposer.org/download/)

4)  spostati nella directory di giuaschool:
`cd C:\xampp\htdocs\giuaschool`

5) installa i componenti di Symfony (ci vorranno parecchi minuti):
`php C:\xampp\composer\composer.phar install`

6) riprova ad installare il database

**Comment by Faobi69** [comment]
Si grazie per le indicazioni ma ottengo un problema il punto 5 da lei elencato, quando eseguo il comando mi compare ciò:


php C:\xampp\composer\composer.phar install
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - ocramius/proxy-manager is locked to version 2.8.0 and an update of this package was not requested.
    - ocramius/proxy-manager 2.8.0 requires php ~7.4.1 -> your php version (7.2.34) does not satisfy that requirement.
  Problem 2
    - ocramius/proxy-manager 2.8.0 requires php ~7.4.1 -> your php version (7.2.34) does not satisfy that requirement.
    - doctrine/migrations 2.2.1 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.8.0].
    - doctrine/migrations is locked to version 2.2.1 and an update of this package was not requested.

**Comment by Faobi69** [comment]
nella cartella composer sono stati creati due file:

1. composer.phar
2. composer-setup.php

però come scritto in precedenza quando eseguo: _php C:\xampp\composer\composer.phar install_
ottengo gli errori sopra elencati

**Comment by Faobi69** [comment]
Ok grazie, adesso ho un problema con l'installazione del database, non ho capito se devo modificare il file .env perchè ottengo:
Access denied for user 'root'@'localhost' (using password: YES)

**Comment by Faobi69** [comment]
Grazie, ultime due cose con un  account docente di tipo coordinatore nella sezione proposte di voto non può inserire le proposte perchè viene critto ciò: "Non è ancora possibile inserire le proposte di voto" e non è neanche possibile sceliere il periodo

invece nell'account amministratore non è possibile accedere al menù "scuola" per configurare le classi e altri deti

**Comment by trinko** [comment]
1) Le proposte di voto sono attive (per qualsiasi docente) solo per lo scrutinio previsto del periodo corrente (primo quadrimestre, finale, ecc.)
Attualmente si può attivare la procedura dello scrutinio solo agendo direttamente sul database; ad es., per inserire lo scrutinio del primo quadrimestre consentendo di inserire le proposte di voto da oggi:
`INSERT INTO `gs_definizione_consiglio` (`modificato`, `data`, `argomenti`, `dati`, `tipo`, `periodo`, `data_proposte`, `struttura`) VALUES (NOW(), '2021-01-18', NULL, NULL, 'S', 'P', '2020-10-01', NULL);`


2) Le menu funzioni per il menu scuola (amministrazione) non sono state ancora sviluppate. 
Si possono modificare le impostazioni nel file "src/DataFixtures/AppFixtures.php" e caricarle con il comando già visto nell'installazione:
`<percorso_installazione_xampp>\xampp\php\php bin\console doctrine:fixtures:load`

**Comment by Faobi69** [comment]
Ok grazie problema quasi risolto, perchè se nel file .env metto prod al posto di dev ed eseguo:
C:\xampp\php\php bin\console server:run
ottengo:
There are no commands defined in the "server" namespace.

  You may be looking for a command provided by the "WebServerBundle" which is currently not installed. Try running "c
  omposer require symfony/web-server-bundle --dev".

volevo provare il progetto su apache senza la modalità di sviluppo

**Comment by trinko** [comment]
Se vuoi usare Apache allora è inutile lanciare il server di Symfony con il comando che hai indicato.

Devi però assicurarti che la configurazione di Apache sia corretta.

**Comment by Faobi69** [comment]
Ok scusa l'ulteriore disturbo, ma non me ne intendo moltissimo di apache quali parametri dovrei modificare su apache?

**Comment by trinko** [comment]
Stavo pensando alle impostazioni sul virtualserver, ma forse non è necessario.
Prova ad accedere direttamente all'indirizzo:
http://localhost/giuaschool/public/

**Comment by Faobi69** [comment]
Niente purtroppo non funziona: The requested URL was not found on this server.

tutte le impostazioni di xampp sono default e i file di giuaschool si trovano in C:\xampp\htdocs\giuaschool
con il server di prova e con env=dev funziona con apache e env=prod o env=dev non funziona.
