### ISSUE TITLE
Vulnerabilità XSS lato docente

### ISSUE THREAD

**Issue by Franck1421** [trinko/giuaschool#153]
Da docente quando si crea una lezione l'argomento e l'attività non vengono filtrati da un possibile attacco XSS come invece viene fatto per le giustificazioni dello studente.
Per ricrerare l'attacco basta creare una lezione da docente e mettere come argomento o attività: 
`</small><script>qualsiasi codice JavaScript</script><small>` .
Testato con successo con:
`</small><script>window.location="https"+":/"+"/www.google.it";</script><small>`
e
`</small><script>alert(1);</script><small>`

**Comment by trinko** [comment]
In effetti è un problema più generale che riguarda il componente Symfony che gestisce le textarea. 
Aprirò un issue sul loro repository.

Per quanta riguarda il registro, sto caricando l'aggiornamento risolutivo.

Grazie per la segnalazione.
