### ISSUE TITLE
Richiesta cambio interfaccia e aggiunte varie

### ISSUE THREAD

**Issue by Denis99s** [trinko/giuaschool#16]
Salve, ho scaricato e installato questo registro, devo dire che è fatto molto bene anche se ci sono delle mancanze e delle cose da modificare, volevo chiedere se è possibile:
1) abilitare il menù scuola per l'amministratore
2) cambiare l'interfaccia del registro di classe in modo che assomigli a grosso modo a quella del registro elettronico classeviva, in modo da visualizzare subito lo stato degli alunni e vedere appunti e/o note disciplinari in maniera più ordinata come nelle foto sottostanti; non me ne intendo moltissimo di programmazione ma penso che sia abbastanza complicato realizzare ciò, però sarebbe molto meglio esteticamente e anche funzionalmente.
![2](https://user-images.githubusercontent.com/74004026/98249262-57870300-1f76-11eb-9897-e4d9eb3e74ac.png)
![eventi](https://user-images.githubusercontent.com/74004026/98249277-5c4bb700-1f76-11eb-97cc-e96a087c4cd7.jpg)
![eventi2](https://user-images.githubusercontent.com/74004026/98249286-5e157a80-1f76-11eb-94b7-cd53a59f460e.jpg)
![3](https://user-images.githubusercontent.com/74004026/98249289-5f46a780-1f76-11eb-9ea0-be3d0f541c99.jpg)
3) aggiungere un opzione che permette di aggiungere dei voti anche senza aver firmato una lezione, utile nel caso si dovesse inserire un voto in una giornata in cui non si ha lezione con quella classe ma si vuole utilizzare la data del giorno in ogni caso.

Sono richieste abbastanza grandi da fare e me ne rendo conto però se in futuro fossero disponibili, l'intero registro sarebbe ancora meglio. Buona giornata

**Comment by trinko** [comment]
Suggerimenti e proposte sono sempre utili e verranno pertanto tenuti presente.
Ma francamente il tempo che posso dedicare allo sviluppo mi basta a appena per soddisfare le richieste provenienti dal mio Istituto.

**Comment by Denis99s** [comment]
Certo, la ringrazio di tenere presenti questi suggerimenti e penso che dal lato di comodità e di ordine sia utile anche per il suo istituto apportare queste modifiche in futuro, cordiali slauti
