### ISSUE TITLE
Studenti Non Si Vedono Dall'area Amministratore

### ISSUE THREAD

**Issue by manuelbarberi** [trinko/giuaschool#161]
Quando vado nel menù studenti/modifica studenti non riesco a vedere la lista ma nel database sono presenti

**Comment by trinko** [comment]
Questo avviene perché hai inserito delle username diverse dal formato standard. Al momento non sono gestiti formati diversi.

Se li stai importando, lascia in bianco la username dello studente e dei genitori.

Se vuoi correggere quelle già inserite, usa il formato:
- studenti:  **utente.sX**
- genitore1: **username_studente.fX**
- genitore2: **username_studente.gX**
X indica una cifra, normalmente **1**, che viene modificata in caso di omonimia.
