### ISSUE TITLE
problema scrutinio

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#168]
quando inserisco la data dell' inserimento delle proposte di voto per il 2 trimestre e provo ad inserire le proposte mi da quest errore
![Immagine 2022-02-07 183455](https://user-images.githubusercontent.com/93207960/152841462-f7bcd8c0-76d9-4033-bd87-8d4148689e06.png)
@trinko mi può aiutare?

**Comment by trinko** [comment]
Per capire cosa succede, devi riportare il contenuto del log, presente nel file **var/log/app_prod_XXX.log**

**Comment by gmontalbano5ct** [comment]
Ok domani provo

**Comment by gmontalbano5ct** [comment]
Ce qualcuno che lo sa fare?

**Comment by sempliciniluigi89** [comment]
Per caso qualcuno è riuscito a risolvere il problema della testata che non
appare in nessun documento?Io ho provato forse per le centesima volta
eseguendo in tutti i modi in cui mi avete suggerito,ma niente,non compare
niente di niente,tutti i documenti sono senza testata.




Il giorno lun 7 feb 2022 alle ore 21:11 gmontalbano5ct <
***@***.***> ha scritto:

**Comment by gmontalbano5ct** [comment]
Lei sa risolvere il mio problema ?

**Comment by sempliciniluigi89** [comment]
Purtroppo non saprei aiutarla,mi dispiace

Il Lun 7 Feb 2022, 21:22 gmontalbano5ct ***@***.***> ha
scritto:
