### ISSUE TITLE
Problema trimestri

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#173]
Quando vado nelle proposte di voto mi spunta soltanto primo quadrimestre e scrutinio finale perché ? Mi potete aiutare?

**Comment by gmontalbano5ct** [comment]
@trinko mi può aiutare

**Comment by trinko** [comment]
Bisogna anzitutto configurare i periodi, andando, come amministratore, in **SISTEMA > PARAMETRI**.
Quindi impostare, per i periodi, il nome e la data finale (compresa nel periodo).

Se serve un terzo periodo (ad es. quando si usano  i trimestri), impostare il nome in **periodo3_nome**

**Comment by gmontalbano5ct** [comment]
Si così ho fatto ma andando ad inserire le proposte di voto mi spunta soltanto primo quadrimestre e scrutinio finale

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by gmontalbano5ct** [comment]
Guardi lei stesso @trinko 
![Screenshot_2022-02-14-20-04-29-221_com android chrome](https://user-images.githubusercontent.com/93207960/153929478-4bf2b00a-0df1-42f0-a03c-033e54033714.jpg)
![Screenshot_2022-02-14-20-04-59-408_com android chrome](https://user-images.githubusercontent.com/93207960/153929495-6ffa4e3b-555b-471b-8371-5cf5f330117f.jpg)

**Comment by gmontalbano5ct** [comment]
Però nella sezione  voti mi spunta primo trimestre secondo trimestre e scrutinio

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by gmontalbano5ct** [comment]
Scusate qualcuno mi sa aiutare ?

**Comment by trinko** [comment]
> Guardi lei stesso @trinko ![Screenshot_2022-02-14-20-04-29-221_com android chrome](https://user-images.githubusercontent.com/93207960/153929478-4bf2b00a-0df1-42f0-a03c-033e54033714.jpg)
> 
> ![IMG_20220214_200834](https://user-images.githubusercontent.com/93207960/153929926-e9dbe98d-894a-4b72-83d3-6ba929924a1b.jpg)

E' errata la configurazione. Se hai 3 trimestri, il primo finisce il 31 gennaio, ma per il secondo hai inserito come data finale il termine dell'anno scolastico. 
Dovrebbe essere qualcosa del tipo:

- **periodo_2_fine**: 2022-04-30

**Comment by gmontalbano5ct** [comment]
Scusi ho lo stesso problema mi può dire se sbaglio @trinko 
![Screenshot_2022-02-22-19-50-16-512_com android chrome](https://user-images.githubusercontent.com/93207960/155199166-b4b3e16a-c7c6-4b40-be10-0e5f65e3144e.jpg)
![Screenshot_2022-02-22-19-50-31-524_com android chrome](https://user-images.githubusercontent.com/93207960/155199181-1ca9e7e2-fc40-4208-9f07-3c571149bbcb.jpg)
![Screenshot_2022-02-22-19-49-57-605_com android chrome](https://user-images.githubusercontent.com/93207960/155199192-16d83d60-4c4d-4e23-b4ac-4bd6fcc79c42.jpg)

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by trinko** [comment]
@gmontalbano5ct 
Mi sembra che la configurazione sia corretta, perché dal menu SCUOLA > SCRUTINI vedi regolarmente le impostazioni anche del secondo trimestre.

Forse c'è qualcosa di errato nella data di fine del primo trimestre (potrebbe sovrapporsi ai periodi successivi) o di fine anno.

**Comment by gmontalbano5ct** [comment]
Ho controllato ma sembra apposto

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by trinko** [comment]
Controlla di aver impostato le date di inizio proposte di voto e inizio scrutini per tutti i periodi. Dal menu SCUOLA > SCRUTINI

**Comment by gmontalbano5ct** [comment]
Ho provato ma nulla
