### ISSUE TITLE
Domanda sul significato della parola "App" usata più volte nel codice

### ISSUE THREAD

**Issue by HiemSword** [trinko/giuaschool#18]
Salve
Di recente mi sono incuriosito nel codice di questo registro elettronico e ho visto che più volte viene menzionata un "app".
Che cosa si intende? Una API forse?

**Comment by trinko** [comment]
Ciao,
se parli della classe App, questa inizialmente doveva servire solo a gestire le App per dispositivi mobili, poi ha inglobato anche le API utilizzate per altri servizi.
Se però intendi l'uso nei nomi dei package del tipo App\Controller\... allora questo è semplicemente lo standard usato da Symfony per indicare i sorgenti dell'applicazione.

**Comment by HiemSword** [comment]
Si intendevo la classe App, ho visto che nel file AppController.php (che immagino sia il controller per l'api) ci sono solo funzioni per entrare nel registro. Mi chiedevo se è possibile aggiungere delle funzioni per ottenere dati dell'utente (voti, pagelle, ecc)? In questo modo si ha anche la possibilità di creare una applicazione per telefoni nativa per guardare voti, lezioni e altro.

**Comment by trinko** [comment]
Si, certo, si può fare. In realtà l'avevo anche messo nella todo-list... 
Ma ci sono altre priorità e non so quando riuscirò ad implementarle.

**Comment by HiemSword** [comment]
Capisco, grazie per il suo tempo
