### ISSUE TITLE
Installazione del registro elettronico da NETSONS 

### ISSUE THREAD

**Issue by nicholas20220** [trinko/giuaschool#187]
Salve, 
Sto provando ad installare il registro elettronico per la mia scuola ma al momento che scarico i file sul mio sito mi appare ERRORE 403  saprebbe dirmi cosa posso fare.
Ringrazio Anticipatamente.

**Comment by manuelbarberi** [comment]
se mi manda i dati di accesso provo ad installarlo io

**Comment by nicholas20220** [comment]
DOVE GLIELI INVIO?

**Comment by manuelbarberi** [comment]
manuelbarberi.mb@libero.it

**Comment by nicholas20220** [comment]
OK

**Comment by nicholas20220** [comment]
Inviata mi faccia sapere se è arrivata grazie.

**Comment by manuelbarberi** [comment]
Arrivata, ora sistemo tutto

**Comment by manuelbarberi** [comment]
registro è php 8.0
netsons non permette di modificarlo. Fallo su altri hosting

**Comment by nicholas20220** [comment]
quale hosting mi consiglia?

**Comment by manuelbarberi** [comment]
altervista

**Comment by nicholas20220** [comment]
ok grazie, ci possiamo ricontattare quando mi sono iscritto su altervista?

**Comment by manuelbarberi** [comment]
si

**Comment by nicholas20220** [comment]
Mi sono arrivate le credenziali di Altervista, gliele ho inviate sulla sua mail

**Comment by manuelbarberi** [comment]
sono arrivate, provvedo ad installare

**Comment by manuelbarberi** [comment]
fatto
mandata mail
