### ISSUE TITLE
Aggiungere "segna come letta"

### ISSUE THREAD

**Issue by alpha4041** [trinko/giuaschool#19]
Sarebbe utile un'opzione per segnare come letta una circolare, senza dover scaricare il documento.

**Comment by trinko** [comment]
Si, è vero.
Appena posso lo aggiungo

**Comment by tommasiangelo01** [comment]
BUONGIORNO,DAL MOMENTO CHE SONO INTERESSATO AD ADOTTARE IL REGISTRO GIUA@SCHOOL NEL MIO ISTITUTO,VORREI SAPERE SE É POSSIBILE AVERE UNA GUIDA DI INSTALLAZIONE O COMUNQUE UN PICCOLO VIDEO CHE ILLUSTRI COME SCARICARE GIUA@SCHOOL ,DAL MOMENTO CHE NON SI EVINCE MOLTO DALLE INFORMAZIONI PRESENTI SU GITHUB .GRAZIE

**Comment by trinko** [comment]
Inserito nell'ultima versione
