### ISSUE TITLE
Problema dirigente scolastico

### ISSUE THREAD

**Issue by scuolagioco** [trinko/giuaschool#191]
Buon pomeriggio, testando il registro mi sono reso conto che quando vado ad accedere con il profilo del dirigente scolastico mi dice utente non riconosciuto. Ho provato anche ad andare su SISTEMA > ALIAS e provare da la ma niente, oppure su SISTEMA > PASSWORD e resettare la password, ma mi compare sempre l’avviso utente non riconosciuto. Sapete aiutarmi?

**Comment by manuelbarberi** [comment]
va abilitato dal cpanel

**Comment by scuolagioco** [comment]
> va abilitato dal cpanel

Mi potrebbe aiutare?

**Comment by trinko** [comment]
> Buon pomeriggio, testando il registro mi sono reso conto che quando vado ad accedere con il profilo del dirigente scolastico mi dice utente non riconosciuto. Ho provato anche ad andare su SISTEMA > ALIAS e provare da la ma niente, oppure su SISTEMA > PASSWORD e resettare la password, ma mi compare sempre l’avviso utente non riconosciuto. Sapete aiutarmi?

Hai provato a reimostare l'utente del dirigente dal menu SCUOLA > DIRIGENTE SCOLASTICO?

**Comment by scuolagioco** [comment]
> > Buon pomeriggio, testando il registro mi sono reso conto che quando vado ad accedere con il profilo del dirigente scolastico mi dice utente non riconosciuto. Ho provato anche ad andare su SISTEMA > ALIAS e provare da la ma niente, oppure su SISTEMA > PASSWORD e resettare la password, ma mi compare sempre l’avviso utente non riconosciuto. Sapete aiutarmi?
> 
> Hai provato a reimostare l'utente del dirigente dal menu SCUOLA > DIRIGENTE SCOLASTICO?

Sisi, ho provato già a reimpostarlo, anche a cambiare il nome utente

**Comment by trinko** [comment]
Ho trovato l'errore nel codice.
La modifica che risolve il problema è nell'ultimo aggiornamento. Consiglio però di aspettare il rilascio della prossima versione, a breve.

In ogni caso, una volta aggiornata l'applicazione, è necessario tornare alla pagina SCUOLA > DIRIGENTE e confermare i dati.
