### ISSUE TITLE
Problema supplenza

### ISSUE THREAD

**Issue by scuolagioco** [trinko/giuaschool#193]
Salve, provando il registro con il dirigente scolastico ci siamo resi conto che non permette di firmare un ora di supplenza all’interno di una classe non assegnata. Selezionando la classe spunta un messaggio (lo allego). Mi sono confrontato privatamente con il Sig. Manuel Barberi e mi ha confermato anche lui che questa situazione avviene anche a lui. Qualcuno saprebbe aiutarci 
![Uploading C828FFA6-400F-4657-AAFB-DB7EB91A5563.jpeg…]()

**Comment by trinko** [comment]
L'immagine del messaggio di errore non è visibile.

Comunque, un docente può firmare come supplenza in qualsiasi classe. 

L'unica eccezione è firmare come supplenza in una classe che appartiene alla propria cattedra: in tal caso si deve firmare regolarmente. La ragione è che il supplente ha delle funzioni limitate (non può mettere voti), ma se si deve fare un'ora aggiuntiva in una propria classe non si possono avere questi limiti.
Naturalmente, per supplenza intendo la sostituzione temporanea di un docente. La supplenza che viene formalmente assegnata per un periodo di tempo, va configurata come cattedra (spuntando la casella supplenza).

**Comment by scuolagioco** [comment]
![D352D32F-F6FD-4411-A456-02F4D7142C7C](https://user-images.githubusercontent.com/96265220/156177224-c3149016-e692-4ed8-b3f4-94c0d705bee7.jpeg)

**Comment by trinko** [comment]
Devi riportare il contenuto del file di log, altrimenti è impossibile capire cosa è successo.
I file di log li trovi nella cartella **var/log/**

PS: nella prossima versione il log è consultabile dal menu di amministrazione SISTEMA > MANUTENZIONE

**Comment by manuelbarberi** [comment]
Devi inserire come materia la supplenza... non è un bug

**Comment by trinko** [comment]
Vedi la documentazione sulla configurazione iniziale:
[documentazione](https://trinko.github.io/giuaschool-docs/configure.html)
