### ISSUE TITLE
Scrutinio finale problema

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#195]
**Descrivi il problema**
Una chiara e sintetica descrizione del problema riscontrato.

**Come riprodurre l'errore**
Passi necessari per riprodurre l'errore, ad esempio:
1. Vai alla pagina ...
2. Inserisci ...
3. Clicca su ...

**File di LOG**
Nel caso di errore di sistema 500, carica il file di log **var/log/prod_xxx.log** (o un suo screenshot)

**Informazioni aggiuntive**
Qualsiasi altra informazione utile in relazione al problema riscontrato.

**Comment by gmontalbano5ct** [comment]
Scusate mi da errore 500 appena prendo le presenze dei docenti e vado avanti qualcuno mi sa aiutare @trinko

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by trinko** [comment]
Devi riportare il contenuto del file di log, altrimenti è impossibile capire cosa è successo. 
I file di logo li trovi nella cartella **var/log/**

PS: nella prossima versione il log è consultabile dal menu di amministrazione SISTEMA > MANUTENZIONE

**Comment by gmontalbano5ct** [comment]
Mi dica lei quale è il problema @trinko 
![16465953241367584003995164665782](https://user-images.githubusercontent.com/93207960/156939215-06769a43-c14c-4dd4-88e8-fbc3158f9d5b.jpg)

**Comment by trinko** [comment]
Dovresti visualizzare i messaggi precedenti, in particolare qualcuno con l'indicazione ERROR.

Quelli riportati sono solo avvisi (WARNING) e di norma non causano un errore di sistema.

**Comment by gmontalbano5ct** [comment]
![Screenshot_2022-03-06-21-31-00-917_com android chrome](https://user-images.githubusercontent.com/93207960/156941017-b19b37a9-c56b-4350-a606-dbd80a3b66bf.jpg)
Ecco @trinko

**Comment by gmontalbano5ct** [comment]
![Screenshot_2022-03-08-22-04-47-027_com android chrome](https://user-images.githubusercontent.com/93207960/157324978-767da47e-b34a-41a0-81d5-9b464fa98736.jpg)
![Screenshot_2022-03-08-22-04-53-402_com android chrome](https://user-images.githubusercontent.com/93207960/157324990-9e3ce73a-6b3c-48cc-9fa9-a3bae10c6b63.jpg)
![Screenshot_2022-03-08-22-05-00-083_com android chrome](https://user-images.githubusercontent.com/93207960/157325004-de40afc5-492e-443b-ad4e-3e9be941f871.jpg)
![Screenshot_2022-03-08-22-05-03-918_com android chrome](https://user-images.githubusercontent.com/93207960/157325018-77d2125d-7d74-44a3-aad2-f5dd0d8d5637.jpg)
Ecco mi può dire quale è il problema?

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by trinko** [comment]
Se hai ancora il problema:
- installa la 1.4.3
- attiva il debug
- riporta il file di log generato (allegalo come file di testo, non usare immagini per cortesia)

**Comment by gmontalbano5ct** [comment]
Ok Grazie domani provo

**Comment by manuelbarberi** [comment]
Io ho fatto così.... dopo aver creato lo scrutinio e dopo che ha portato l'errore sono andato da cpanel e ho impostato come passo 3... da qui mi ha fatto andare avanti

**Comment by gmontalbano5ct** [comment]
@manuelbarberi come accedo al cpanel ?

**Comment by manuelbarberi** [comment]
Se sei da altervista non puoi... nemmeno da x10hosting

**Comment by sempliciniluigi89** [comment]
Ma questo è un problema serio,perché siamo in tanti ad avere il sistema
hosting altervista o x10hosting, penso che in qualche modo questo problema
debba essere risolto, diversamente non si può fare

Il Sab 19 Mar 2022, 16:29 Manu ***@***.***> ha scritto:

**Comment by gmontalbano5ct** [comment]
@trinko  aggiornando alla nuova versione mi da lo stesso problema come faccio?

**Comment by trinko** [comment]
Esegui i seguenti passi:
- da amministratore, attiva il debug dalla pagina SISTEMA > MANUTENZIONE
- rifai la procedura che genera l'errore
- torna in amministrazione ed estrai il log, dalla pagina SISTEMA > MANUTENZIONE, indicando l'orario di inizio di quando hai eseguito la procedura che genera l'errore
- allega qui il documento di testo del log scaricato (eventualmente puoi censurare alcuni dati che non è opportuno pubblicare)

Alla fine, ti consiglio di disattivare il debug, che appesantisce inutilmente l'esecuzione dell'applicazione.

**Comment by gmontalbano5ct** [comment]
ok provo grazie

**Comment by gmontalbano5ct** [comment]
ok che ordinamento ha? @trinko

**Comment by trinko** [comment]
L'ordinamento serve solo per la visualizzazione su certi documenti, per cui si può modificare a piacere.
Io  la inserisco sempre come ultima:  999.

**Comment by gmontalbano5ct** [comment]
ok grazie funziona tutto correttamente
