### ISSUE TITLE
Installazione

### ISSUE THREAD

**Issue by manuelbarberi** [trinko/giuaschool#197]
Quando vado ad installare la versione aggiornata di giuaschool mi porta un errore; is_executable(): open_basedir restriction in effect. File(/usr/bin/unoconv) is not within the allowed path(s): (/membri/registromanututorial/:/membri2/registromanututorial/:/membri/.dummy/)
In /membri/registromanututorial/src/Install/Installer.php:497

**Comment by trinko** [comment]
Ho modificato l'installer. 
L'ultimo aggiornamento dovrebbe risolvere il problema.
