### ISSUE TITLE
Errori durante l'installazione

### ISSUE THREAD

**Issue by manuelbarberi** [trinko/giuaschool#198]
Errore Undefined variable $pipes
In /membri/registromanututorial/vendor/symfony/console/Terminal.php:162 

Sono riuscito a correggere l'errore ma adesso porta questo: 

In CacheItem.php line 201: Failed to save key Impossibile eseguire i comandi per creare il database.

In CacheItem.php line 201: Failed to save key "App%5CEntity%5CScrutinio" of type array: touch(): Utime failed: Operation not permitted
In /membri/registromanututorial/vendor/ symfony/cache/CacheItem.php:201 doctrine:schema:drop [--em EM] [--dump-sql] [-f|--force] [--full-database] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--]

**Comment by trinko** [comment]
Devi controllare i permessi della cartella della cache: **var/cache** e **var/cache/prod**
L'utente del web server deve avere i permessi di scrittura.

**Comment by manuelbarberi** [comment]
Ho già tentato... non funziona

**Comment by trinko** [comment]
L'ultimo aggiornamento potrebbe risolvere il problema.

**Comment by manuelbarberi** [comment]
Porta ancora questo errore: Errore nell'esecuzione dei comandi per l'inizializzazione del database.
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '----- TABELLA CONFIGURAZIONE -----' at line 1

**Comment by trinko** [comment]
Pare sia un errore per la sintassi dei commenti su MySQL (io uso MariaDB e non ci sono probemi).
Ho modificato il codice nell'ultimo aggiornamento.

**Comment by manuelbarberi** [comment]
Ok, tento di installarlo e le dico se porta ancora errori

**Comment by manuelbarberi** [comment]
Errore nell'esecuzione dei comandi per l'inizializzazione del database.
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--- TABELLA CONFIGURAZIONE --' at line 1

Ancora qui

**Comment by manuelbarberi** [comment]
Trovato il problema: bisogna togliere ---TABELLA CONFIGURAZIONE---
