### ISSUE TITLE
Proposte di voto

### ISSUE THREAD

**Issue by manuelbarberi** [trinko/giuaschool#202]
Errore durante l'inserimento delle proposte di voto.

**Comment by trinko** [comment]
Se hai ancora il problema:
- installa la 1.4.3
- attiva il debug
- riporta il file di log generato (allegalo come file di testo)

**Comment by manuelbarberi** [comment]
[2022-03-15_08-05.log](https://github.com/trinko/giuaschool/files/8250915/2022-03-15_08-05.log)

**Comment by trinko** [comment]
Ho capito il problema.
Manca la gestione di alcuni template per il secondo quadrimestre. Vedo di sistemarlo appena posso.

**Comment by trinko** [comment]
Per risolvere il problema:
- installa l'ultimo aggiornamento
- da amministratore, vai in SCUOLA > SCRUTINI e conferma nuovamente i periodi inseriti

**Comment by manuelbarberi** [comment]
Ok, ora provo a installare

**Comment by manuelbarberi** [comment]
Funziona tutto, grazie mille...
