### ISSUE TITLE
Aiuto @manuelbarberi

### ISSUE THREAD

**Issue by scuolagioco** [trinko/giuaschool#206]
Buongiorno, chiedo, se è possibile, assistenza al sig. @manuelbarberi per l'aggiornamento del database del registro. Avevo mandato già una mail ma, non avendo avuto risposta, scrivo un articolo su questa piattaforma. Se qualcuno si offre di aiutarmi ne sarei riconoscente.

**Comment by manuelbarberi** [comment]
Guarda nelle discussioni la sezione demo

**Comment by scuolagioco** [comment]
> Guarda nelle discussioni la sezione demo

Il problema non è l'installazione del registro, l'ha già installato lei per noi giorni fa, il problema è come aggiornare il registro, non riesco a capire come fare. Se lei mi fa un breve tutorial (anche video se vuole e lo manda via mail scuolagioco2@gmail.com) riuscirò a capire così da non doverla più disturbare @manuelbarberi

**Comment by scuolagioco** [comment]
Qualcuno mi saprebbe aiutare? Ho un grandissimo problema con il registro e devo obbligatoriamente aggiornarlo per risolvere. @trinko @manuelbarberi
