### ISSUE TITLE
Errore durante l'aggiornamento

### ISSUE THREAD

**Issue by scuolagioco** [trinko/giuaschool#208]
Buongiorno, ho aggiornato il registro ma quando vado alla pagina iniziale esce questo errore. La prego di rispondermi al più presto @trinko 

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\EnvNotFoundException: Environment variable not found: "LOG_LEVEL". in /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/EnvVarProcessor.php:171 Stack trace: #0 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/Container.php(422): Symfony\Component\DependencyInjection\EnvVarProcessor->getEnv('string', 'LOG_LEVEL', Object(Closure)) #1 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/ContainerBuilder.php(1581): Symfony\Component\DependencyInjection\Container->getEnv('LOG_LEVEL') #2 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/ContainerBuilder.php(1440): Symfony\Component\DependencyInjection\ContainerBuilder->getEnv('LOG_LEVEL') #3 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(222): Symfony\Component\DependencyInjection\ContainerBuilder->resolveEnvPlaceholders('env_fc613cb1b5d...', true, NULL) #4 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php(63): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder->resolveEnvPlaceholders('env_fc613cb1b5d...', true) #5 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php(184): Symfony\Bundle\MonologBundle\DependencyInjection\MonologExtension->levelToMonologConst('env_fc613cb1b5d...', Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder)) #6 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/monolog-bundle/DependencyInjection/MonologExtension.php(101): Symfony\Bundle\MonologBundle\DependencyInjection\MonologExtension->buildHandler(Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder), 'main', Array) #7 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Symfony\Bundle\MonologBundle\DependencyInjection\MonologExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder)) #8 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #9 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/Compiler/Compiler.php(94): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #10 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/ContainerBuilder.php(762): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder)) #11 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/http-kernel/Kernel.php(596): Symfony\Component\DependencyInjection\ContainerBuilder->compile() #12 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/http-kernel/Kernel.php(136): Symfony\Component\HttpKernel\Kernel->initializeContainer() #13 /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/http-kernel/Kernel.php(196): Symfony\Component\HttpKernel\Kernel->boot() #14 /membri/scuolagiocoregistro1/registrogiua/public/index.php(29): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #15 {main} thrown in /membri/scuolagiocoregistro1/registrogiua/vendor/symfony/dependency-injection/EnvVarProcessor.php on line 171

**Comment by trinko** [comment]
Hai eseguito la procedura andando alla pagina:   **nome_sito/install/index.php** ?

Se l'hai già eseguita, controlla il file **.env**: forse manca questa riga
`LOG_LEVEL='warning'`
