### ISSUE TITLE
Domanda sul come creare le pagelle

### ISSUE THREAD

**Issue by Franck1421** [trinko/giuaschool#21]
Salve,
potrebbe spiegarmi passo per passo come creare delle pagelle nel registro prima della fine reale dell'anno?

**Comment by trinko** [comment]
Le pagelle non sono gestite dal registro elettronico ma da un software esterno di gestione delle funzioni della segreteria.

Il registro giua@school è pensato per gestire le funzioni svolte dai docenti, non quelle del personale amministrativo. Per la pagelle viene quindi gestito lo scrutinio con la definizione dei voti finali. Poi i dati vengono esportati e caricati sul software di gestione della segreteria: noi usiamo un software commerciale per la gestione della segreteria e portroppo importare i dati non è un lavoro semplice (ci sono molti limiti imposti dal produttore).

**Comment by Franck1421** [comment]
Quindi generare delle pagelle per testare il registro è impossibile?

**Comment by trinko** [comment]
Scusa, mi sono spiegato male.
Intendevo che non è prevista la stampa della pagella formale, quella con il modello classico che solitamente archiviano le segreterie. 
Naturalmente la comunicazione dei voti finali viene presentata agli alunni e ai genitori, e viene anche creato un documento PDF con l'intestazione dell'istituto per la comunicazione dei voti.
Se vuoi fare una prova, è al momento necessario inserire dei dati direttamente nel database per attivare lo scrutinio (non c'è ancora una procedura nelle funzioni di gestione del registro). 
Ti posso indicare in seguito i passaggi necessari.

**Comment by Franck1421** [comment]
Si grazie mi servirebbero i passaggi

**Comment by trinko** [comment]
Allora, questi sono i passaggi da seguire.

1. installa la gestione dei docker sul tuo computer, come indicato nella pagina principale del progetto
1.  se avevi già scaricato l'applicazione, è neccessario aggiornarla all'ultima versione, altrimenti non vedrai il file che ho aggiunto da poco; pertanto, solo se l'avevi già scaricata, devi cancellare l'immagine precedente con il comando:
`docker rmi ghcr.io/trinko/giuaschool:latest`
2. avvia il server con il comando:
`docker run -d --rm --name gs_test -p 8080:80 ghcr.io/trinko/giuaschool:latest`

1. una volta che il server è avviato, devi entrare nella macchina virtuale con il comando:
`docker exec -it gs_test /bin/bash`

1. ora bisogna eseguire il comando seguente per passare all'ambiente di sviluppo:
`sed -r -i -e "s/^APP_ENV\s*=.*$/APP_ENV=dev/" .env`

1. adesso si può inserire nel database la configurazione dello scrutinio finale:
`php bin/console doctrine:fixtures:load --group DefinizioneScrutinioFixtures --append`

1. ora bisogna uscire dall'ambiente di sviluppo:
`sed -r -i -e "s/^APP_ENV\s*=.*$/APP_ENV=prod/" .env`

1. e uscire dalla macchina virtuale:
`exit`

1. a questo punto pui usare il browser per andare all'indirizzo
 [http://localhost:8080](http://localhost:8080)

1. accedi all'applicazione utilizzando **admin** come utente e come password

Tieni presente che una volta attivato lo scrutinio, i docenti della classe possono inserire le proposte di voto, mentre il coordinatore gestisce lo scrutinio. 
E' meglio usare un utente dello STAFF, che può gestire lo scrutinio di qualsiasi classe. Usa la classe 3A che ha già alcune cattedre impostate.

- vai al menu DOCENTI -> CATTEDRE per vedere chi sono i docenti della classe
- vai al menu DOCENTI -> STAFF per vedere chi sono gli utenti dello staff e copia il nome utente di uno di loro
- vai al menu SISTEMA -> ALIAS e inserisci il nome utente per impersonare l'utente dello staff o del docente

Puoi usare queste guide per la gestione dello scrutinio (sono quelle usate nel nostro Istituto lo scorso anno):

[giuaschool_manuale_scrutinio_finale_coordinatori.pdf](https://github.com/trinko/giuaschool/files/7463437/giuaschool_manuale_scrutinio_finale_coordinatori.pdf)
[giuaschool_manuale_scrutinio_finale_docenti.pdf](https://github.com/trinko/giuaschool/files/7463438/giuaschool_manuale_scrutinio_finale_docenti.pdf)

**Comment by Franck1421** [comment]
@HiemSword, che hosta il registro "finto", ha provato tutti i passaggi però c'è un problema: quando si tenta di creare gli scrutini per il registro è come se non esistessero più alunni in quella determinata classe quando in realtà ci sono. 
Questo è come si presenta il registro al momento della creazione della pagella:
![IMG-20211103-WA0005](https://user-images.githubusercontent.com/51267237/140183024-218b5670-9ffa-4f33-aa3a-1b0b1a301a43.jpg)

**Comment by trinko** [comment]
Purtroppo mancano dati per la visualizzazione corretta delle pagine.
Posso inserirli in modo che facciano parte dell'ambiente di test, ma fra qualche giorno.

**Comment by trinko** [comment]
Nell'ultima versione sono presenti i dati di test per visualizzare le pagelle.
E' sufficiente installare l'ultima versione e, una volta eseguito il login come amministratore:
- andare al menu ALUNNI -> MODIFICA per vedere chi sonogli alunni della classe 3A
- andare al menu SISTEMA -> ALIAS e inserire il nome utente per impersonare l'alunno scelto
- andare al menu PAGELLE e scegliere il periodo per visualizzare le pagelle dei vari scrutini

**Comment by HiemSword** [comment]
Ho scaricato l'ultima verisone (v1.4.1) ma quando vado a guardare le pagelle mi dice che l'alunno non è inserito in nessuna classe
![studente](https://user-images.githubusercontent.com/34164621/141693228-070bf84d-55cc-4116-96e6-d9dcfcf6734c.PNG)

Ho provato anche ad entrare come coordinatore e iniziare lo scrutinio ma anche la mi blocca e mi dice che non ci sono dati per gli scrutini
![docente](https://user-images.githubusercontent.com/34164621/141693294-050cac60-f702-4973-bfc9-3a2d6eee6f02.PNG)

Ho per caso saltato un passaggio?

**Comment by trinko** [comment]
Hai ragione, bisogna caricare i dati di test. 
Riporto la procedura completa:

1. usa i contenitori docker per scaricare l'ultima versione dell'applicazione. Potrebbe ancora essere presente in cache la versione precedente, quindi consiglio di provare a rimuoverla per sicurezza: 
`docker rmi ghcr.io/trinko/giuaschool:latest`

2. scarica e avvia il server:
`docker run -d --rm --name gs_test -p 8080:80 ghcr.io/trinko/giuaschool:latest`

3. una volta che il server è avviato, devi entrare nella macchina virtuale con il comando:
`docker exec -it gs_test /bin/bash`

4. ora bisogna eseguire il comando seguente per passare all'ambiente di sviluppo:
`sed -r -i -e "s/^APP_ENV\s*=.*$/APP_ENV=dev/" .env`

5. elimina il database esistente e ricreane uno vuoto:
`php bin/console doctrine:database:drop --force`
`php bin/console doctrine:database:create`
`php bin/console doctrine:schema:update --force`

6. carica i nuovi dati:
`php bin/console doctrine:fixtures:load --group Test`

7. ora bisogna uscire dall'ambiente di sviluppo:
`sed -r -i -e "s/^APP_ENV\s*=.*$/APP_ENV=prod/" .env`

8. e uscire dalla macchina virtuale:
`exit`

9. a questo punto pui usare il browser per andare all'indirizzo
http://localhost:8080

**Comment by HiemSword** [comment]
Grazie mille! Ora funziona tutto alla perfezione
