### ISSUE TITLE
Impossibilità aggiornamento registro con servizio  altervista e x10hosting 

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#211]
Ma questo è un problema serio,perché siamo in tanti ad avere il sistema hosting altervista o x10hosting ,con l'ultimo aggiornamento non ci viene permesso di aggiornare effettivamente il registro, penso che in qualche modo questo problema debba essere risolto, diversamente non si può fare

**Comment by trinko** [comment]
Non capisco perché è impossibile aggiornare il registro. Se è possibile l'installazione, lo sarà anche l'aggiornamento.

**Comment by sempliciniluigi89** [comment]
Glielo chiedo a nome di tutto l'istituto se sarebbe disposto ad
aggiornamelo, attendo un suo riscontro per comunicarle le credenziali
dell'hosting .Grazie

Il Sab 19 Mar 2022, 18:50 Antonello Dessì ***@***.***> ha
scritto:

**Comment by sempliciniluigi89** [comment]
Attendo un suo riscontro

Il Sab 19 Mar 2022, 18:58 Luigi Semplicini ***@***.***> ha
scritto:

**Comment by sempliciniluigi89** [comment]
É urgente

**Comment by sempliciniluigi89** [comment]
Mi faccia sapere

**Comment by trinko** [comment]
Mi spiace, ma per quanto mi riguarda, rubo già tantissime ore al mio tempo libero per lo sviluppo dell'applicazione: non posso occuparmi anche di questo tipo di assistenza.
Posso solo indicare le note indicative nella [documentazione](https://trinko.github.io/giuaschool-docs/update.html).

**Comment by sempliciniluigi89** [comment]
Allora diversamente non posso fare, pertanto andremo avanti senza aggiornare il registro.,mi spiace .Grazie

**Comment by scuolagioco** [comment]
> Allora diversamente non posso fare, pertanto andremo avanti senza aggiornare il registro.,mi spiace .Grazie

buongiorno, se scrivi a [supporto@giuademo.x10 (mailto:supporto@giuademo.x10.mx) potrai richiedere assistenza e il sig. Barberi ti aggiornerà il registro in pochissimi tempo.

**Comment by sempliciniluigi89** [comment]
Ho provato a mandare diversi mail ,ma con scarsi risultati ,non ho ottenuto nessuna risposta

**Comment by sempliciniluigi89** [comment]
@scuolagioco Per caso lei sarebbe disposto ad aggiornarmi il registro elettronico?Purtroppo non sono capace di eseguire questo aggiornamento che ci è tanto necessario in quanto con l'ultimo aggiornamento sono state sistemate diversi bug.Mi faccia sapere se è disponibile in modo da inviarle le credenziali dell'hosting sulla mail privata .Come hosting uso x10hosting

**Comment by sempliciniluigi89** [comment]
La preside vorrebbe già il registro aggiornato e funzionale per domani

**Comment by scuolagioco** [comment]
> @scuolagioco Per caso lei sarebbe disposto ad aggiornarmi il registro elettronico?Purtroppo non sono capace di eseguire questo aggiornamento che ci è tanto necessario in quanto con l'ultimo aggiornamento sono state sistemate diversi bug.Mi faccia sapere se è disponibile in modo da inviarle le credenziali dell'hosting sulla mail privata .Come hosting uso x10hosting

Mi dispiace ma neanche io sono competente nel campo, ecco perchè ho mandato le mail al sig. Barberi. Ma ha mandato già le email alla posta elettronica che le ho indicato sopra? E' diversa da quella personale del sig. Barberi. Ritenti in quella mail.

**Comment by sempliciniluigi89** [comment]
Va bene ,grazie!

Il Dom 20 Mar 2022, 10:54 Scuola Gioco ***@***.***> ha
scritto:
