### ISSUE TITLE
Creazione utente genitore obbligatorio e importazione CSV alunni

### ISSUE THREAD

**Issue by scuolagioco** [trinko/giuaschool#212]
Salve, aggiungendo gli alunni tramite il registro e non importando un file CSV mi rendo conto che è obbligatorio aggiungere entrambi i genitori. Credo che questa opzione di rendere obbligatoria l'aggiunta di un genitore debba essere eliminata o almeno aggiungere un'impostazione che potrà essere scelta dalla segreteria. Credo che quando si va a creare l'alunno non debba essere obbligatorio, come vediamo in Argo ScuolaNext, aggiungere un genitore. Non so se c'è un’opzione apposita già all'interno del registro, se qualcuno ne è a conoscenza lo faccia presente. Ultima cosa… ho provato ad importare gli alunni anche da CSV, ma non riesco a capire quali campi sono obbligatori e quali no. Ho provato solo con le informazioni dell'alunno (nome, cognome, data di nascita, sesso, codice fiscale, città e classe) ma richiede sempre anche i nominativi dei genitori. Inoltre quando vado ad inserire la data di nascita come 04/02/2005 mi segnala "la data 4/2/2005 non è valida". Mi sapreste aiutare?

**Comment by trinko** [comment]
Non è obbligatorio indicare i genitori. Gli utenti genitori vengono creati comunque, anche se saranno fittizi.
Leggi la documentazione e usa i file di importazione di esempio inseriti:
- [documentazione](https://trinko.github.io/giuaschool-docs/configure.html#importazione-degli-utenti)

**Comment by scuolagioco** [comment]
> Non è obbligatorio indicare i genitori. Gli utenti genitori vengono creati comunque, anche se saranno fittizi. Leggi la documentazione e usa i file di importazione di esempio inseriti:
> 
> * [documentazione](https://trinko.github.io/giuaschool-docs/configure.html#importazione-degli-utenti)

Ok grazie mille

**Comment by sempliciniluigi89** [comment]
@scuolagioco  Per caso lei sarebbe disposto ad aggiornarmi il registro elettronico?Purtroppo non sono capace di eseguire questo aggiornamento che ci è tanto necessario in quanto con l'ultimo aggiornamento sono state sistemate diversi bug.Mi faccia sapere se è disponibile in modo da inviarle le credenziali dell'hosting sulla mail privata .Come hosting uso x10hosting

**Comment by scuolagioco** [comment]
@trinko ho visto la documentazione come ha detto lei e ho scaricato il vostro file csv ed ho provato ad importare quello, ma mi dice sempre questo errore: # 1: email (genitore1): Il valore inserito non è un indirizzo email valido. [mutio@gmail.com] cosa devo fare?

**Comment by trinko** [comment]
> @trinko ho visto la documentazione come ha detto lei e ho scaricato il vostro file csv ed ho provato ad importare quello, ma mi dice sempre questo errore: # 1: email (genitore1): Il valore inserito non è un indirizzo email valido. [[mutio@gmail.com](mailto:mutio@gmail.com)] cosa devo fare?

Se l'email è corretta, l'errore è dovuto al fatto che esiste già nel sistema. Due utenti non possono avere la stessa email.
