### ISSUE TITLE
Configurazione server mail fallita

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#217]
Buonasera, una volta ricevuto il link per la configurazione del server mail , l'ho inviato all'utente supporto@giuademo.x10.mx chiedendo di aiutarmi nella configurazione , l'utente è stato molto gentile e ha fatto il possibile, ma purtroppo ha detto che ha provato senza ottenere nessun risultato , ora come posso fare ?E' un bel problema , come hosting uso x10hosting

**Comment by trinko** [comment]
Senza informazioni sul tipo di errore generato e sul tipo di configurazione scelta, non posso dire niente.

E' probabibile che l'hosting usato blocchi la possibilità di spedizione delle email.
