### ISSUE TITLE
Documenti,relazioni,programmi non funziona

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#218]
Buonasera ,accedendo come docente ,ho cercato di caricare la relazione di Italiano e il programma , solo che appena clicco su aggiungi per aggiungere il file relazione o programma ,automaticamente il programma mi riporta sul portale di accesso dove devo inserire nuovamente username e password.

**Comment by trinko** [comment]
Dovresti attivare il debug e riportare il log generato. In questo modo si può capire megio cosa succede.
