### ISSUE TITLE
Installazione su altervista

### ISSUE THREAD

**Issue by rodolfo024** [trinko/giuaschool#22]
Buonasera, ho provato la versione dimostrativa e incuriosito vorrei provare ad adoperare la versione "completa" installando il programma su un mio sito. Volevo sapere se esiste la possibilità di mettere il programma su AlterVista oppure è impossibile.
Grazie e ottimo lavoro!

**Comment by trinko** [comment]
Anzi tutto, tieni presente che l'unica differenza tra la versione demo e quella reale è nei dati precaricati. Nella versione demo non sono attive alcune funzioni (come lo scrutinio) perché mancano alcune impostazioni. Modificandole puoi attivare tutto quello che è previsto.

Su Altervista potrebbe funzionare, ma dovresti:

1. installare la versione demo su un computer
2. esportare il database e importarlo su quello del sito Altervista
3. copiare tutta la cartella "giuaschool" e caricarla sul sito Altervista

A questo punto, però, non so se Altervista ti permetta di scegliere una sottocartella (all'interno dello spazio che ti viene assegnato) per la visualizzazione delle pagine sul web server. Infatti l'unico contenuto che deve essere esposto sul sito internet è quello all'interno della cartella "public". Tutto il resto del codice deve essere inaccessibile per gli  utenti.
Se Altervista non ti consente questa impostazione il sito non funzionerà. E anche se riuscissi a farlo funzionare ci sarebbero grossi rischi dal punto di vista della sicurezza.

**Comment by rodolfo024** [comment]
Grazie di avermi risposto. Da quello che mi dici, ho riscoperto un mio altro vecchio host che avevo che forse permette di separare parte pubblica e parte privata. Unica cosa è che, al contrario del semplice caricamento dei dati via ftp, mi risulta molto più complesso riuscire a creare il database da poi importare. Pertanto ti chiedo molto gentilmente se ne hai la possibilità e non ti costa uno sforzo enorme, di potermi, nella modalità che più ritieni opportuna, farmi avere il file database pulito da poter poi importare nel cloud.
Grazie ancora

**Comment by trinko** [comment]
Di seguito trovi l'esportazione del database di test con i dati precaricati **giuaschool-test.txt** e quello vuoto, con solo l'utente amministratore, **giuaschool-test-vuoto.txt**:

[giuaschool-test.txt](https://github.com/trinko/giuaschool/files/7463243/giuaschool-test.txt)
[giuaschool-test-vuoto.txt](https://github.com/trinko/giuaschool/files/7463244/giuaschool-test-vuoto.txt)

**Comment by rodolfo024** [comment]
Ciao, ho caricato il db e messo i file sul sito, ma quando mi collego ad esso alla cartella /public mi compare questo errore:
Fatal error: require(): Failed opening required '/membri/[nomedominio]/vendor/autoload.php' (include_path='.:') in /membri/[nomedominio]/config/bootstrap.php on line 5.
Grazie e scusa per il disturbo arrecato.

**Comment by trinko** [comment]
Immagino che tu abbia già controllato se effettivamente il file indicato è presente sul server.

Controlla quindi i permessi di accesso del file e delle varie directory del percorso: il file deve essere leggibile dal proprietario del processo che sta eseguendo il webserver (ad es. www-data per i server apache); le directory devono essere leggibili ed eseguibili dallo stesso utente.

Con il comando "ls -la" dovresti vedere i permessi.

**Comment by rodolfo024** [comment]
Credo di aver “trovato” il problema guardandomi intorno nelle varie issues perché io non ho adoperato mai symfony e quindi non si sono creati quei file, infatti non li trovo. Symfony ho tentato di scaricarlo ma non mi riesce tenendo conto che prima di tutto serve visual c++ per le librerie che non posso installare sul computer che uso per questo lavoro. Non vorrei risultare troppo _rompi scatole_, ma se ci fosse la possibilità di passarmi la cartella già “lavorata” in modo da andare avanti nella sperimentazione mi faresti una enorme cortesia.
Grazie e scusa ancora la scocciatura

**Comment by rodolfo024** [comment]
Ok. Adesso ho le idee un po' più chiare. 
Io dopo aver installato correttamente Doker Desktop ho eseguito sul cmd il codice per il programma di prova e quindi scaricato l'immagine. Una volta fatto questo cosa devo fare? Questo è il punto in cui non riesco ad andare più avanti. Il programma di prova funziona ma non riesco a trovare nel computer i files.
Grazie e scusami ancora il disturbo

**Comment by trinko** [comment]
Manda in esecuzione l'applicazione con il comando:
`docker run -d --rm --name gs_test -p 80:80 ghcr.io/trinko/giuaschool:latest` 

Quindi usa il comando seguente per copiare la cartella giuaschool su una cartella del tuo pc:
`docker cp gs_test:/var/www/giuaschool percorso_cartella`

**Comment by rodolfo024** [comment]
Allora, un problema l'abbiamo risolto, ovvero non c'è più l'errore di prima, d'altro canto ne appare un altro, sempre per un file che non c'è:
Fatal error: require_once(): Failed opening required '/membri/[nomedominio]/vendor/composer/autoload_real.php' (include_path='.:') in /membri/[nomedominio]/vendor/autoload.php on line 5

manca questo file atuoload_real.php

**Comment by trinko** [comment]
Questo è strano. E' possibile che non siano stati copiati tutti i file.
Prova il seguente comando per vedere se ti trova il file nell'installazione del docker:
`docker cp gs_test:/var/www/giuaschool/vendor/composer/autoload_real.php  percorso_cartella/autoload_real.php`

**Comment by valerio-bozzolan** [comment]
AlterVista è un hosting condiviso gratuito che quindi non fornisce alcun requisito di performance o alcun'altra garanzia contrattuale. Sullo stesso server per rientrare nei costi fanno girare centinaia se non migliaia di altri siti web estranei.

Sarebbe meglio almeno acquistare una VPS per avere un contratto con garanzie chiare.

**Comment by trinko** [comment]
@rodolfo024 Per avere maggiori informazioni sull'errore del server, visualizza i file presenti nella cartella di log:  '/membri/[nomedominio]/var/log/'

**Comment by rodolfo024** [comment]
Nella cartella che mi hai segnalato ci sono questi file che però contengono delle informazioni riguardanti la demo perché si fa menzione di "raoul martino" e riferimento a "localhost"

https://drive.google.com/drive/folders/11H8sVAsl8pY3uG_mAL2NxJuNfoc215dR?usp=sharing

**Comment by trinko** [comment]
Sembra quindi che il server non riesca neanche ad eseguire i file principali che generano i log.
Se aspetti qualche giorno, ho intenzione di aggiungere su GitHub la distribuzione del codice dell'applicazione generato correttamente e pronto all'uso. 

Mi ci vuole un po' di tempo però.

**Comment by rodolfo024** [comment]
Grazie. Tranquillo non c'è furia!

**Comment by rodolfo024** [comment]
Ciao, come stanno procedendo i lavori?

**Comment by trinko** [comment]
La nuova versione contiene l'installazione semplificata.

Scaricare dal pulsante DOWNLOAD RELEASE
