### ISSUE TITLE
Richiesta demo

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#23]
Buongiorno ,sarebbe possibile avere la demo ?Se sì ,come si può fare dal momento che usiamo filezilla ?

**Comment by rodolfo024** [comment]
La demo non si adopera con filezilla. Bisogna installare correttamente l'applicativo Docker desktop e successivamente dal cmd invocare i codici che sono indicati della sezione di questo sito dedicata alla demo. La versione dimostrativa funziona solo in locale e una volta spento il computer o invocato il comando di chiusura si perde tutto quello che si è fatto. Il programma ha un database con dati di prova che possono essere modificati, sempre entro i limiti di quanto suddetto. La versione dimostrativa inoltre non consente di modificare i dati relativi al nome della scuola, del d.s., le materie, l'orario ecc...

**Comment by sempliciniluigi89** [comment]
Dal momento che non ho trovo nessuna guida di installazione , vi è possibile pubblicare un piccolo video tutorial che spieghi passo per passo come installare il tutto ?Grazie

**Comment by trinko** [comment]
@sempliciniluigi89 
Se aspetti qualche giorno, ho intenzione di aggiungere su GitHub la distribuzione del codice dell'applicazione generato correttamente e pronto all'uso. In questo modo l'installazione sarà più semplice.

Mi ci vuole un po' di tempo però.

**Comment by tommasiangelo01** [comment]
Benissimo,più o meno quando sarebbe il rilascio ?Grazie mille,non vedo l'ora

**Comment by sempliciniluigi89** [comment]
Sarebbe a dir poco favoloso!!!Più o meno in questa settimana dovrebbe avvenire il rilascio?

**Comment by sempliciniluigi89** [comment]
Se l'installazione  fosse facile come LAMPSCHOOL sarebbe stupendo ,senza uso di docker ,cmd etc...

**Comment by sempliciniluigi89** [comment]
Sarebbe veramente bello ,non vedo l'ora che avvenga questo rilascio che dovrebbe semplificare l'installazione così come avete detto voi.

**Comment by trinko** [comment]
La nuova versione contiene l'installazione semplificata. 

Scaricare dal pulsante DONLOAD RELEASE
