### ISSUE TITLE
Ultimo aggiornamento

### ISSUE THREAD

**Issue by manuelbarberi** [trinko/giuaschool#233]
Dropping database schema... In AbstractPlatform.php line 398: Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platfo rm may not support it. doctrine:schema:drop [--em EM] [--dump-sql] [-f|--force] [--full-database] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--]

**Comment by trinko** [comment]
Errore molto strano, che non riesco a riprodurre.

Mi pare di capire che stai installando su un database che in precedenza era utilizzato da un'altra applicazione. Questo database contiene un campo con tipo ENUM che non è supportato dal database manager (doctrine).

L'unica soluzione è cancellare a mano tutte le tabelle esistenti nel vecchio database o meglio, se puoi farlo, cancellare l'intero database.

**Comment by manuelbarberi** [comment]
Funziona tutto correttamente ora... grazie mille
