### ISSUE TITLE
DB Error nel caricamento delle fixtures

### ISSUE THREAD

**Issue by zerai** [trinko/giuaschool#237]
**Descrivi il problema**

il comando symfony `bin/console doctrine:fixtures:load`
produce il seguente errore:
`An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Supplenza' for key 'UNIQ_6505E4FF54BD530C'`

**Indica come riprodurre l'errore**

- Run dell'immagine di dev

'docker run -d --rm --name gs_test -p 443:443 ghcr.io/trinko/giuaschool-devl:latest'

- Accesso al container

'docker exec -it a0c4fad4da28 bash'

- Run del comando symfony

'php ./bin/console doctrine:fixtures:load'

**File di LOG**
Se necessario, allega il file di log (menu **SISTEMA > MANUTENZIONE**)
![Screenshot from 2022-05-07 12-56-54](https://user-images.githubusercontent.com/2405279/167251672-943c8761-35a1-4387-a87c-26ae3076898d.png)

**Comment by trinko** [comment]
Se vuoi eseguire i test, puoi anche usare l'immagine di test giuaschool-test che ha già caricato i dati necessari.

Comunque, utilizzando l'ambiente DEV, devi correggere il comando di caricamento delle fixtures. 
Se vuoi utilizzare i dati di test devi caricare solo quelli:
`php bin/console doctrine:fixtures:load -n --group=Test`
Altrimenti, se vuoi l'ambiente con solo i dati essenziali per il funzionamento del registro, devi eseguire:
`php bin/console doctrine:fixtures:load -n --group=App`

**Comment by zerai** [comment]
Grazie per le info, potrebbe essere utile aggiungerle alla doc, insieme alle istruzioni docker delle 2 immagini.
