### ISSUE TITLE
Guide Docenti/Famiglie

### ISSUE THREAD

**Issue by Lucaccc** [trinko/giuaschool#25]
Salve, volevo sapere se esistessero delle guide consultabili per docenti e famiglie…in modo da velocizzare l’apprendimento legato all’uso della piattaforma.

**Comment by trinko** [comment]
Le guide, anche se non sempre aggiornate alle ultime modifiche, si trovano nella cartella **public/doc**

[Vedi qui](https://github.com/trinko/giuaschool/tree/master/public/doc)
