### ISSUE TITLE
PROBLEMA PROPOSTE DI VOTO FINALI

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#251]
Quando vado su scrutinio e scelgo scrutinio finale metto dettaglio voti pur già avendo inserito dei voti non mi spunta la media dello scrutinio finale
![Immagine 2022-05-19 164444](https://user-images.githubusercontent.com/93207960/169545793-4a8431c0-0529-4a5b-a0b5-34d1919a416c.png)
@trinko  qual'è il problema?

**Comment by trinko** [comment]
C'è un errore nel codice che non permette la visualizzazione corretta nel caso di utilizzo dei trimestri.
Cerco di risolvere appena posso.

**Comment by trinko** [comment]
Il problema dovrebbe essere risolto con l'ultimo aggiornamento.

**Comment by gmontalbano5ct** [comment]
@manuelbarberi potrebbe farmi l aggiornamento o quanto meno spiegarmi tutti i passaggi?

**Comment by gmontalbano5ct** [comment]
> Il problema dovrebbe essere risolto con l'ultimo aggiornamento.

Ok grazie

**Comment by gmontalbano5ct** [comment]
> @manuelbarberi potrebbe farmi l aggiornamento o quanto meno spiegarmi tutti i passaggi?

@manuelbarberi

**Comment by gmontalbano5ct** [comment]
@manuelbarberi

**Comment by gmontalbano5ct** [comment]
@trinko scusi mi può spiegare come fare l'aggiornamento del registro?

**Comment by trinko** [comment]
La procedura di aggiornamento è descritta nella documentazione:
[aggiornamento](https://trinko.github.io/giuaschool-docs/update.html)

**Comment by gmontalbano5ct** [comment]
Ho provato tempo fa ma non riesco

**Comment by gmontalbano5ct** [comment]
@trinko con file zilla posso caricare tutti i file ?

**Comment by trinko** [comment]
> @trinko con file zilla posso caricare tutti i file ?

Si. Una volta caricati i file,  devi eseguire la procedura andando all'indirizzo:
- **http://nome_sito/install/index.php** o **http://nome_sito/public/install/index.php**

**Comment by gmontalbano5ct** [comment]
Ok mi può per favore spiegare anche come configurare il file env?

**Comment by gmontalbano5ct** [comment]
Perché non c'è più nel server

**Comment by gmontalbano5ct** [comment]
C'è bisogno di rimetterlo? @trinko

**Comment by gmontalbano5ct** [comment]
devo scaricare la versione realise? giusto? @trinko

**Comment by trinko** [comment]
Si, devi scaricare l'ultimo aggiornamento: 
[ultimo aggiornamento](https://github.com/trinko/giuaschool/releases/download/latest-build/giuaschool-build-latest.zip)

Il file ".env" sul tuo server c'è già sicuramente, altrimenti non funzionerebbe niente. Carica i file sul server e poi vail alink per eseguire l'aggiornamento:

    **http://nome_sito/install/index.php** o **http://nome_sito/public/install/index.php**

**Comment by gmontalbano5ct** [comment]
Scusa ma con quale software li carico i file ? Via FTP

**Comment by gmontalbano5ct** [comment]
Perché sono 29000 file

**Comment by gmontalbano5ct** [comment]
Filezilla è lento

**Comment by trinko** [comment]
Di solito il servizio di hosting ti dovrebbe permettere di caricare in FTP solo il file compresso (.zip) e poi decomprimerlo direttamente sul server. E' la cosa più veloce

**Comment by gmontalbano5ct** [comment]
Non riesco a caricarlo lo zip come si fa ?

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
