### ISSUE TITLE
Annotazioni su registro error500

### ISSUE THREAD

**Issue by rodolfo024** [trinko/giuaschool#255]
Mi sono accorto che dopo aver fatto l'aggiornamento del registro, quando dal registro di classe clicco sul "aggiungi" per inserire un'annotazione compare l'errore 500.
[2022-05-25_12-17.log](https://github.com/trinko/giuaschool/files/8770136/2022-05-25_12-17.log)

**Comment by trinko** [comment]
L'ultimo aggiornamento risolve il problema.

**Comment by rodolfo024** [comment]
Ho effettuato l'aggiornamento ed il problema si è risolto!
