### ISSUE TITLE
Problema scrutinio finale

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#257]
Salve ho un problema che provando a simulare lo scrutinio finale, c'è un alunno che per motivi di salute si è assentato molto superando il limite stabilito io andando avanti con la procedura di scrutinio arrivato alle problematiche di assenza mi dice nessuno, ma andando a controllare il numero di assenze il numero di ore fatte dall alunno sono 323, quelle che si possono fare sono 305 
Allego foto 
![IMG_20220529_162348](https://user-images.githubusercontent.com/93207960/170874386-954e682e-001f-449b-ac2f-f7562f14e7a9.jpg)
![IMG_20220529_162410](https://user-images.githubusercontent.com/93207960/170874391-5d6f0f4b-57f9-4ce7-a891-a760acdeca48.jpg)
Mi sapete aiutare?

**Comment by gmontalbano5ct** [comment]
@trinko mi sa aiutare

**Comment by trinko** [comment]
Il calcolo delle ore di assenza allo scrutinio è quello ufficiale, quello riportato nella pagina delle assenze è indicativo. In questo caso, quindi, non supera il limite previsto ed è corretto.

Il motivo della differenza di calcolo è dovuto al fatto che nella scheda di assenza vengono sommate TUTTE le ore di assenza, ma allo scrutinio devono essere calcolate SOLO le ore relative alle varie materie.... Mancaranno quindi le ore di assenza che sono state fatte in ore firmate come SOSTITUZIONE, che non è una materia curricolare.
Se ci pensi è esattamente la stessa cosa che succedeva con i registri cartacei: nello scrutinio erano riportate le ore di assenza dal registro personale dei docenti, che ovviamente avevano segnato SOLO le ore svolte da loro. Eventuali sostituzioni temporanee rimanevano solo sul registro di classe, ma le relative assenze non erano conteggiate.

Quindi, il calcolo fatto allo scrutinio è quello corretto, devo aggiornare la procedura della pagina delle assenze (quando ne avrò il tempo).

Se vuoi fare un controllo per verificare le ore di assenza, dovresti andare sul registro e vedere nei giorni di assenza quante ore firmate come SOSTITUZIONE sono presenti.

**Comment by gmontalbano5ct** [comment]
Ok grazie mille. Ma la nuova versione quando sarà disponibile?

**Comment by trinko** [comment]
> 

Se tutto va bene, tra un paio di giorni.

**Comment by gmontalbano5ct** [comment]
Un altra domanda ma nella pagella di vedono le ore totalizzate giusto?

**Comment by trinko** [comment]
Si, esatto.

**Comment by gmontalbano5ct** [comment]
Ok grazie
