### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by rodolfo024** [trinko/giuaschool#26]
Rieccoci qua, adesso va tutto molto meglio e il file log viene letto e scritto, infatti compare questo errore: 
[app_prod-2021-11-15.log](https://github.com/trinko/giuaschool/files/7540773/app_prod-2021-11-15.log)
Grazie!

**Comment by trinko** [comment]
Non hai modificato la configurazione di accesso al database, per cui l'applicazione non riesce a connettersi a mysql.

Devi modificare il file **.env** che contiene le configurazioni fondamentali. In particolare l'impostazione per la connessione al database è la seguente:
`DATABASE_URL='mysql://root:root@localhost:3306/giuaschool?serverVersion=mariadb-10.4.13'`

La sintassi della stringa è la seguente:

`mysql://<utente>:<password>@<host>/database?serverVersion=<versione>`

I parametri vengono forniti da chi offre il servizio di hosting del sito
- `<utente>`: utente per l'accesso al server database
- `<password>`: password per l'accesso al server database
- `<host>`: server del database indicato  come indirizzo IP o nome della macchina completo del dominio; 
- `<database>`: nome del database
- `<versione>`: versione del server mysql o mariadb (non dovrebbe essere un parametro fondamentale, ma viene raccomandato dagli sviluppatori di Symfony)

**Comment by rodolfo024** [comment]
Grazie. Adesso finalmente il sito funziona però c'è un ultimo passaggio ovvero, il registro è identico alla demo, sia per i dati ma soprattutto per il fatto che da admin le voci di "Scuola" sono disabilitate.

**Comment by Lucaccc** [comment]
> Grazie. Adesso finalmente il sito funziona però c'è un ultimo passaggio ovvero, il registro è identico alla demo, sia per i dati ma soprattutto per il fatto che da admin le voci di "Scuola" sono disabilitate.

Buongiorno, vorrei farle una domanda: alla fine ha installato la versione semplificata dell'installazione? tramite altervista?
Sto avendo alcuni problemi e magari, a parità di condizioni, saprebbe aiutarmi...

**Comment by rodolfo024** [comment]
Non ho installato il registro su Altervista ma non ci dovrebbe essere differenza. Io ho trasferito tutti i file all'interno della cartella dell'host e come legge sopra modificato il file .env con le informazioni relative al mio database. A questo punto però, visto che il database che è fornito della cartella è quello demo, per adattarlo alla mia versione dimostrativa ho dovuto lavorare per inserire gli alunni e modificare le informazioni relative all'istituto mediante il pannello di phpmyadmin direttamente sulle tabelle. Però se intanto riesce a far funzionare correttamente il sito con le informazioni di prova è un buon risultato.

**Comment by Lucaccc** [comment]
> Non ho installato il registro su Altervista ma non ci dovrebbe essere differenza. Io ho trasferito tutti i file all'interno della cartella dell'host e come legge sopra modificato il file .env con le informazioni relative al mio database. A questo punto però, visto che il database che è fornito della cartella è quello demo, per adattarlo alla mia versione dimostrativa ho dovuto lavorare per inserire gli alunni e modificare le informazioni relative all'istituto mediante il pannello di phpmyadmin direttamente sulle tabelle. Però se intanto riesce a far funzionare correttamente il sito con le informazioni di prova è un buon risultato.

Io sono arrivato a installare il registro e mi trovo nella pagina di accesso, ma dice che le credenziali sono errate...(ovvero quelle fornite dal sistema, "admin" come username e password).
Lei non ha avuto questo problema?

**Comment by rodolfo024** [comment]
No, io non ho avuto questo problema. Provi ad andare da phpmyadmin nella tabella "utente" e quando riconosce l'utente "admin" dovrebbe essere il secondo, clicchi modifica e dove c'è la password inserisca, senza includere le virgolette, "$argon2id$v=19$m=65536,t=4,p=1$HdeOZpWRt/GRrwMOKxuVUQ$nQUnVK+5I+W8SgeQCmVFh6Z4B5NhamMdoD37zqsZncA". Questo dovrebbe corrispondere alla pw "admin".

**Comment by Lucaccc** [comment]
> $argon2id$v=19$m=65536,t=4,p=1$HdeOZpWRt/GRrwMOKxuVUQ$nQUnVK+5I+W8SgeQCmVFh6Z4B5NhamMdoD37zqsZncA

A breve provo, grazie.
Le faccio sapere, ma non credo sia questo il problema...non capisco...

**Comment by Lucaccc** [comment]
> $argon2id$v=19$m=65536,t=4,p=1$HdeOZpWRt/GRrwMOKxuVUQ$nQUnVK+5I+W8SgeQCmVFh6Z4B5NhamMdoD37zqsZncA

Non funziona...la password inserita era corretta, ma non riesco ancora ad accedere.

**Comment by rodolfo024** [comment]
Quindi c’era quella stringa nel campo password della tabella?

**Comment by Lucaccc** [comment]
> Quindi c’era quella stringa nel campo password della tabella?

Si.
Credo di aver risolto, ma ora ho un altro problema: sono riuscito ad entrare, ma ho dei dati , credo, dimostrativi.
Come devo procedere?

**Comment by rodolfo024** [comment]
immagino che non funzionino i bottoni del menù "scuola" vero?

**Comment by Lucaccc** [comment]
> immagino che non funzionino i bottoni del menù "scuola" vero?

Esatto.

**Comment by rodolfo024** [comment]
Io ho fatto in modo non proprio ortodosso: tranne che per inserire i docenti e le cattedre che sono riuscito a modificare dal sito, per il resto per modificare il nome della scuola, la sede, e soprattutto fare piazza pulita delle classi e dei mille e rotti account ho fatto tutto da phpmyadmin... Come intuibile non è il modo più corretto ecco però è l'unico con cui sono riuscito ad ottenere un qualcosa di funzionante e personalizzato, seppur con ancora qualche bug irrisolto come l'intestazione dei pdf che per 1/3 è con i nuovi dati e il resto con quelli vecchi.

**Comment by Lucaccc** [comment]
> Io ho fatto in modo non proprio ortodosso: tranne che per inserire i docenti e le cattedre che sono riuscito a modificare dal sito, per il resto per modificare il nome della scuola, la sede, e soprattutto fare piazza pulita delle classi e dei mille e rotti account ho fatto tutto da phpmyadmin... Come intuibile non è il modo più corretto ecco però è l'unico con cui sono riuscito ad ottenere un qualcosa di funzionante e personalizzato, seppur con ancora qualche bug irrisolto come l'intestazione dei pdf che per 1/3 è con i nuovi dati e il resto con quelli vecchi.

Io anche credo di fare così...è l'unico modo...
Per il resto funziona correttamente?
Non vorrei importare tutti i dati e poi dover riniziare da capo...

**Comment by rodolfo024** [comment]
Se si fa in questo modo giocoforza lo si fa funzionare. Per il resto per quello che ho potuto vedere in queste prime 24h di uso apparentemente funziona tutto in modo corretto. Unica cosa che se dal menù admin in alunni si clicca su modifica sembra non esserci nessun alunno mentre se si clicca su una classe gli alunni ci sono eccome. Questo temo possa influire sugli scrutini che per ora sono disattivati, ma soprattutto influisce se dal lato preside si vuole vedere tutte le info riguardo l'andamento di tutti gli studenti non compare nulla per quel motivo. Se invece si fa dal lato coordinatore non ci sono problemi. 
In definitiva, in linea di massima va, però non va al 100%.

**Comment by sempliciniluigi89** [comment]
Mi scusi,prima domanda :dove si trova la cartella il "file .env"? Seconda domanda Io uso filezilla e Altervista  e ho scaricato la versione semplificata , per effettuare l'upload dei file dovrei  spostare l'intera cartella giuschool così come sta scaricato in upload o solo una specifica cartella o file? @rodolfo024 , terza domanda :una volta caricati i dati , ossia i file ,per accedere al registro elettronico ,su quale file devo andare di preciso che mi porti su browser per l'installazione ?

**Comment by Lucaccc** [comment]
> Se si fa in questo modo giocoforza lo si fa funzionare. Per il resto per quello che ho potuto vedere in queste prime 24h di uso apparentemente funziona tutto in modo corretto. Unica cosa che se dal menù admin in alunni si clicca su modifica sembra non esserci nessun alunno mentre se si clicca su una classe gli alunni ci sono eccome. Questo temo possa influire sugli scrutini che per ora sono disattivati, ma soprattutto influisce se dal lato preside si vuole vedere tutte le info riguardo l'andamento di tutti gli studenti non compare nulla per quel motivo. Se invece si fa dal lato coordinatore non ci sono problemi. In definitiva, in linea di massima va, però non va al 100%.

Perfetto, grazie.

**Comment by Lucaccc** [comment]
> Se si fa in questo modo giocoforza lo si fa funzionare. Per il resto per quello che ho potuto vedere in queste prime 24h di uso apparentemente funziona tutto in modo corretto. Unica cosa che se dal menù admin in alunni si clicca su modifica sembra non esserci nessun alunno mentre se si clicca su una classe gli alunni ci sono eccome. Questo temo possa influire sugli scrutini che per ora sono disattivati, ma soprattutto influisce se dal lato preside si vuole vedere tutte le info riguardo l'andamento di tutti gli studenti non compare nulla per quel motivo. Se invece si fa dal lato coordinatore non ci sono problemi. In definitiva, in linea di massima va, però non va al 100%.

Salve, una domanda: è riuscito a impostare gli scrutini anche per il primo periodo? A me escono solo quelli finali..

**Comment by sempliciniluigi89** [comment]
Buongiorno, ho fatto l'upload dei file con filezilla, allego foto .Una volta effettuato l'upload dei file cosa devo fare?
https://user-images.githubusercontent.com/93823125/142477211-a3bd221a-8bad-461d-84d8-166194027ae0.png

**Comment by Lucaccc** [comment]
> immagino che non funzionino i bottoni del menù "scuola" vero?

@trinko Saprebbe dirci come sbloccarlo?

**Comment by mondinimirko** [comment]
Buonasera, la sezione scuola non è attiva come riferito #24 
Ho risposto a questa questione in #32
