### ISSUE TITLE
Problema crediti convertiti per le classi 5°

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#270]
Non in tutti gli alunni si visualizza nel tabellone la conversione dei crediti
Allego foto
![IMG_20220611_212801](https://user-images.githubusercontent.com/93207960/173202189-d49f9a5d-9423-4bbc-9c32-96ceccef6019.jpg)
Perché? Come risolvo? @trinko

**Comment by trinko** [comment]
C'e' anzitutto un errore nella pagina, perché sono invertite le colonne del credito di quinta con quello precedente: in allegato la correzione.
Ma il problema sono i dati inseriti per il credito precedente che è sicuramente errato: il credito totale NON può superare i 40 punti. Non vengono visualizzati quindi i crediti errati.

Per risolvere, questa è la procedura:

1. scarica e decomprimi il file allegato; quindi caricalo sul server nella cartella **templates/coordinatore/documenti**, sovrascrivendo il file esistente;
2. con utente amministratore, svuota la cache: **SISTEMA > MANUTENZIONE > SVUOTA CACHE**
3. sempre da amministratore, vai in **ALUNNO > MODIFICA**: per ogni alunno controlla il credito della classe terza e quarta, ed eventualmente modificalo col valore corretto;
4. terminata la correzione, con utente PRESIDE o STAFF riapri lo scrutinio della quinta e torna indietro sino alla pagina dell'esito di ammissione/non ammissione;
5. procedi coi passi successivi, riconfermando tutto, senza modifiche, sino alla chiusura dello scrutinio

A questo punto i crediti precedenti dovrebbero essere correttamente visibili, nel verbale, nel tabellone di riepilogo e nel tabellone degli esiti.


[scrutinio_tabellone_F.html.twig.zip](https://github.com/trinko/giuaschool/files/8885442/scrutinio_tabellone_F.html.twig.zip)
