### ISSUE TITLE
Problema scrutinio per alunni con giudizio sospeso

### ISSUE THREAD

**Issue by gmontalbano5ct** [trinko/giuaschool#272]
Come faccio? qual è il problema? @trinko

**Comment by trinko** [comment]
Non ho capito quale è il problema. Manca il voto?
In ogni caso mi pare tu stia usando uno smartphone: consiglio di utilizzare almeno un tablet perché la visualizzazione dei dati può essere un problema su uno schermo piccolo.

Se il problema è il voto, hai cliccato per modificare sul singolo voto? Cosa succede se clicchi sul pulsante dell'esito?

In ogni caso: attiva il debug, riesegui l'operazione, estrai il log e postalo. Poi disattiva il debug.

**Comment by gmontalbano5ct** [comment]
Ok

**Comment by gmontalbano5ct** [comment]
@trinko

**Comment by trinko** [comment]
Scusa, avevo capito che il problema era nello scrutinio finale a riguardo dell'esito di sospensione del giudizio. 

Invece stai svolgendo lo scrutinio sospeso: il codice di questa procedura non è stato ancora adeguato alle modifiche inserite nello scrutinio finale. Verrà fatto entro la fine di giugno.

Comunque, il problema è che sono stati inseriti dei parametri per poter gestire i voti finali in modo personalizzato: in futuro sarà possibile stabilire, ad es., il voto minimo per tipologia di materia.

**Comment by trinko** [comment]
> Come faccio a risolvere scusi?

Consiglio di aspettare che esca l'apposito aggiornamento, entro la fine di giugno. Del resto lo scrutinio sospeso non si può svolgere a giugno.

Si può provare a copiare il file **templates/coordinatore/voti_F.html.twig** in **templates/coordinatore/voti_E.html.twig** (sovrascrivendolo) e svuotare la cache. Non è detto che funzioni.

**Comment by gmontalbano5ct** [comment]
Aspetto l aggiornamento quando uscirà?

**Comment by gmontalbano5ct** [comment]
Scusi a che punto è con la modifica? @trinko

**Comment by trinko** [comment]
> Scusi a che punto è con la modifica? @trinko

Probabilmente riesco a concluderla entro questo fine settimana.

**Comment by trinko** [comment]
L'ultimo aggiornamento ha la gestione corretta per lo scrutinio degli alunni con giudizi sospeso.
[ultimo aggiornamento](https://github.com/trinko/giuaschool/releases/download/update-v1.4.4/giuaschool-update-v1.4.4.zip)

Tieni presente che se avevi già iniziato uno scrutinio, è bene ripartire dall'inizio, perché potrebbero esserci dei dati inconsistenti.

**Comment by gmontalbano5ct** [comment]
ok grazie

**Comment by gmontalbano5ct** [comment]
@trinko ci sono problemi e ho installato la versione precedente perchè appena andavo nella sezione scrutini dava errore 500 non so perchè...

**Comment by trinko** [comment]
Se attivi il debug e riporti il log degli errori, forse riesco a capire cosa succede.

**Comment by trinko** [comment]
> @trinko ci sono problemi e ho installato la versione precedente perchè appena andavo nella sezione scrutini dava errore 500 non so perchè...

Probabilmente avevi già iniziato uno scrutinio degli alunni con giudizio sospeso: ho dovuto modificare la codifica di alcuni valori, per cui i dati inseriti non vengono riconosciuti e possono portare a vari errori.

Si può risolvere eseguendo i seguenti comandi sul database (ad esempio usando PHPMyadmin):

`UPDATE gs_definizione_consiglio SET periodo = 'G' WHERE periodo = 'E'; `
`UPDATE gs_scrutinio SET periodo = 'G' WHERE periodo = 'E'; `

**Comment by gmontalbano5ct** [comment]
grazie
