### ISSUE TITLE
problema installazione registro

### ISSUE THREAD

**Issue by nicholas20220** [trinko/giuaschool#277]
salve ho un problema mentre installo questo registro elettronico. Le volevo chiedere se mi potesse aiutare. grazie @
![D990EA3C-F502-4561-ACAF-FEB758FCC680](https://user-images.githubusercontent.com/100447937/174167751-35205f6d-c389-4edb-a5d4-966ebd4575ab.png)
QUESTA È LA FOTO

**Comment by sempliciniluigi89** [comment]
Come vede ,stiamo ancora aspettando i video tutorial sul nuovo canale youtube che comprendono anche l'installazione del registro stesso ,in questo modo abbiamo una fonte visiva ma soprattutto una guida che ci dice passo a passo quello che dobbiamo fare senza sbagliare o saltare passaggi .

**Comment by nicholas20220** [comment]
scusi ma come si chiama il canale youtube?

**Comment by sempliciniluigi89** [comment]
https://www.youtube.com/channel/UCVmP0GavypniGv7MapL84fw - questo è il link...
