### ISSUE TITLE
Preside Non Configurabile

### ISSUE THREAD

**Issue by manuelbarberi** [trinko/giuaschool#284]
Quando configuro il preside mostra un avviso dicendo che devo selezionare la spunta attiva o disattiva ma non è presente.

**Comment by trinko** [comment]
Il file allegato dovrebbe risolvere il problema:

- scarica il file, decomprimilo e caricalo nella cartella **src/Controller/**, andando a sovrascrivere il file esistente;
- svuota la cache dal menu **SISTEMA > MANUTENZIONE**

Fammi sapere se il problema è risolto.

[ScuolaController.php.zip](https://github.com/trinko/giuaschool/files/9019827/ScuolaController.php.zip)

**Comment by manuelbarberi** [comment]
Problema risolto
