### ISSUE TITLE
AIUTO INSTALLAZIONE GIUASCHOOL 

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#30]
Buongiorno, ho fatto l'upload dei file con filezilla, allego foto .Una volta effettuato l'upload dei file cosa devo fare?

https://user-images.githubusercontent.com/93823125/142477211-a3bd221a-8bad-461d-84d8-166194027ae0.png

**Comment by mondinimirko** [comment]
Buonasera, deve popolare il db importanto il file .sql all'interno del db del sito web. Successivamente dovrà iniziare a modificare i parametri che le interessano nei vari file .php.

Saluti.

**Comment by sempliciniluigi89** [comment]
Buonasera,non mi ha risposto in merito alla problematica del mio collega
che vuole adottare il registro giuaschool nel suo istituto

Il giorno dom 5 dic 2021 alle ore 20:46 Antonello Dessì <
***@***.***> ha scritto:
