### ISSUE TITLE
ATTIVAZIONE MENU SCUOLA

### ISSUE THREAD

**Issue by lilianaverretti** [trinko/giuaschool#32]
BUONASERA,QUALCUNO DI VOI MI SAPREBBE DIRE COME SI FA AD ATTIVARE IL MENU SCUOLA DEL REGISTRO GIUASCHOOL?GRAZIE

**Comment by mondinimirko** [comment]
Buonasera il menu SCUOLA non è disponibile come anche riferito qua #24
Sto iniziando a lavorarci un po' ma non so dare tempistiche in quanto il lavoro da fare è abbastanza articolato e il lavoro porta via molto tempo. 

_La invito a non utilizzare il maiuscolo quando scrive_

**Comment by sempliciniluigi89** [comment]
Secondo me è come se fosse disattivato in qualche modo ,altrimenti non si spiega in quanto compare in grigia rispetto alle altre voci

**Comment by mondinimirko** [comment]
Guardi @trinko in #24 ha detto chiaramente che il menu non è stato sviluppato. C'è bella differenza tra far vedere qualcosa da un menu e fare in modo che quello che fate sia effettivamente riflesso nel DB.
