### ISSUE TITLE
impossibilità supplenza docente di classe e ...

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#33]
Buonasera ,vorrei solo riportarvi una piccola problematica ,ossia il registro non permette al docente del consiglio di classe di effettuare la supplenza nella stessa classe dove insegna ,è alquanto strano 
Un'altra piccola critica sta nella procedura di giustifica da parte dei genitori:una volta che il genitore giustifica gli risulta ancora la possibilità di modificare , come mai?Una volta giustificato non si dovrebbe più modificare alcun dato.Ultimo problema riguarda lo scrutinio che non è proprio permesso ,ho provato sia come docente coordinatore che come preside e mi dice che non sono presenti  dati sullo scrutinio .Inoltre non permette di inviare direttamente le credenziali ai diretti interessati via mail

**Comment by trinko** [comment]
La supplenza nella propria classe è inutile: si fa lezione normale accedendo direttamente alle proprie classi. Se si potesse entrare nella propria classe come SUPPLENTE, ci sarebbero dei limiti alle operazioni che si possono fare (non si possono inserire voti). Si ricorda che per SUPPLENZA si intende una sostituzione temporanea di un'ora, non una nomina di un supplente per un certo periodo di tempo: in questo secondo caso viene configurata una cattedra.

La giustificazione inserita dai genitori, deve essere poi VALIDATA dal docente: infatti il docente controlla la giustificazione e la considera valida (ma potrebbe anche non considerarrla valida e lasciarla così). Il genitore può quindi modificare la giustitificazione sino a quando viene validata. Dopo la validazione non potrà più modificarla.

La gestione dello scrutinio ha diversi passaggi che richiedono l'inserimento di dati per funzionare. Le procedure, inoltre, non sono modificabili in modo semplice.

**Comment by sempliciniluigi89** [comment]
Buongiorno ,il problema è che fra pochi giorni ,prima delle vacanze di natale chiude il trimestre e non sappiamo come fare con il problema degli scrutini.

**Comment by trinko** [comment]
Vedi:

[#35](https://github.com/trinko/giuaschool/issues/35)
