### ISSUE TITLE
Accesso con google 

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#34]
Buongiorno ,sto cercando di abilitare l'accesso ai docenti e alunni mediante Google, colo che ogni volta che cliccano su "entra con GOOGLE" esce la seguente scritta 
https://user-images.githubusercontent.com/93823125/143680176-f39c7cec-8458-47e7-85ce-c8f86dc0cdbf.png

**Comment by zerai** [comment]
Nel tuo .env file ci sono vari parametri con riferimento a google, vanno configurati con i dati di accesso forniti da google.
Guida autenticazione Oauth di google https://developers.google.com/identity/protocols/oauth2/openid-connect#registeringyourapp

**Comment by trinko** [comment]
Nessuna attività negli  ultimi 30 giorni: segnalazione chiusa.
