### ISSUE TITLE
Gestione scrutini

### ISSUE THREAD

**Issue by trinko** [trinko/giuaschool#35]
Buongiorno ,il problema è che fra pochi giorni ,prima delle vacanze di natale chiude il trimestre e non sappiamo come fare con il problema degli scrutini.

_Originally posted by @sempliciniluigi89 in https://github.com/trinko/giuaschool/issues/33#issuecomment-981053936_

**Comment by trinko** [comment]
Tieni presente che la gestione scrutini può richiedere diverse modifiche nel codice per adattarla alla tua scuola, per cui adattarla in così poco tempo può essere un problema.
Comunque ti indico la procedura per attivare lo scrutinio:

Scarica il file seguente che contiene i dati da inserire nel database.
[abilita_scrutinio.txt](https://github.com/trinko/giuaschool/files/7613485/abilita_scrutinio.txt)

Prima di eseguire il comando puoi modificare le impostazioni che trovi nelle 3 righe iniziali:
- **TIPO**: indica il periodo; **P** per il primo trimestre/quadrimestre, **F** per lo scrutinio finale, **S** per lo scrutinio degli alunni con giudizio sospeso
- **DATA_SCRUTINIO**: indica la data di inizio degli scrutini, si può usare per evitare che venga attivata la procedura prima del previsto;
- **DATA_PROPOSTE**: indica la data di inizio per l'inserimento delle proposte di voto da parte dei docenti, si può usare per evitare che vengano inserite prima del previsto.

Una volta che avrai eseguito il comando sul database, lo scrutinio sarà attivo. A questo punto:

1. tutti i docenti potranno inserire le proprie proposte di voto (a partire dalla data indicata in precedenza);
2. i coordinatori potranno accedere alla funzione scrutinio e iniziare lo scrutinio;
3. lo staff può gestire lo scrutinio di qualsiasi classe.

Puoi guardare il seguente manuale di gestione dello scrutinio del primo quadrimestre/trimestre per vedere come funziona attualmente:

[giuaschool_manuale_scrutinio_primo_quadrimestre.pdf](https://github.com/trinko/giuaschool/files/7613510/giuaschool_manuale_scrutinio_primo_quadrimestre.pdf)

**Comment by sempliciniluigi89** [comment]
Buongiorno ,ho  provato grazie alle vostre indicazioni ad eseguire lo scrutinio di una classe fittizia e devo dire che a grandi linee procede tutto bene ,ma ce solo un problema: mi fa inserire le proposte per tutte le materie ,eccetto ed.civica in quanto ,quando clicco culla matita di inserimento della proposta di ed.civica c'è un caricamento infinito che non permette di inserire di conseguenza la proposta solo ed esclusivamente in ed.civica ,questo è un bel problema perché ho provato ad andare avanti lo stesso senza inserire la proposta in ed.civica e non mi permette neanche questo

**Comment by sempliciniluigi89** [comment]
Ovviamente parlo della versione semplificata

**Comment by trinko** [comment]
Il problema che hai riscontrato era dovuto ad alcune modifiche fatte per la gestione degli scrutini finali e che non avevo riportato sulla gestione del primo quadrimestre. Ora ho sistemato la cosa.

Per non reinstallare tutto, puoi scaricare il file compresso seguente e copiare nelle cartelle di destinazione:
[giuaschool.zip](https://github.com/trinko/giuaschool/files/7614548/giuaschool.zip)


Ricorda di cancellare la cache, altrimenti potresi non vedere le modifiche. Per cancellare la cache, svuota la cartella **var/cahe/prod**

**Comment by rodolfo024** [comment]
Anche io ho questo problema e fatto quanto hai detto, svuotando la cache e sovrascrivendo i files non è cambiato nulla di una virgola.
