### ISSUE TITLE
Aggiornamento versione semplificata

### ISSUE THREAD

**Issue by rodolfo024** [trinko/giuaschool#36]
Buonasera, volevo chiedere come bisogna procede per aggiornare la versione semplificata. Basta scaricare e fare l'upload del sorgente "giuaschool_master" o bisogna reinstallare la cartella "giuaschool_release"? Grazie.

**Comment by trinko** [comment]
Se vuoi installare le ultime modifiche non incluse nella versione pubblicata nella pagina principale, attaulamente la **1.4.1**, devi scaricare la **build-release**, che contiene la versione semplificata aggiornata.

Per scaricare la **build-release**:

1. vai alla [pagina delle build](https://github.com/trinko/giuaschool/actions/workflows/build.yml)
2. apri la prima della lista (ultima build) cliccando sul suo nome
3. vai alla fine della pagina per visualizzare la scheda **Artifacts** e scarica il file indicato come **build-release**
4. sovrascrivi la versione installata con il contenuto della **build-release** (evita di sovrascrivere i file di configurazione che hai modificato per la tua installazione, come il **.env**)
5. cancella la cache, svuotando la cartella **var/cache/prod**

Potrebbe essere necessario effettuare anche modifiche alla struttura del database.
