### ISSUE TITLE
GIUSTIFICHE

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#37]
Buongiorno, oggi mentre inserivo l'uscita anticipata di un alunno mi sono reso conto che non richiede la giustifica, cosa che fa con il ritardo e l'assenza .

**Comment by trinko** [comment]
Nel nostro modo di gestire le cose, le uscite non si giustificano, ma si autorizzano da parte della dirigenza,  dietro una richiesta preventiva del genitore. La richiesta non è sempre formalizzata, e spesso è orale: per questo attualmente non c'è ancora una gestione nel registro.

E' chiaro che la richiesta equivale in sostanza alla giustificazione, per cui dovrò implementarla prima o poi.
