### ISSUE TITLE
Titolo pagina agenda 

### ISSUE THREAD

**Issue by 8HELL** [trinko/giuaschool#42]
Se si entra con un account studente o genitore il titolo della pagina resta sempre agenda genitori anche usando l'account gsuite alunno.
Sia il nome pagina che il titolo nella pagina in se' resta uguale in tutti i casi 
![issue](https://user-images.githubusercontent.com/94806504/144566686-71cc0c84-a92f-44fb-8df8-e5f5524e8c7b.PNG)

**Comment by trinko** [comment]
Corretto nell'ultimo aggiornamento.
