### ISSUE TITLE
AIUTO ISTITUTO 

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#43]
Buongiorno, un mio ex collega che ora si trova in un altro istituto, ha espresso il desiderio di adottare il registro GIUASCHOOL per tanti motivi nella scuola scuola.Ebbene sì, utilizza come hosting Altervista e dal momento che mi ha chiesto una mano , non ho saputo dire di no.Le procedure da me effettuate sul suo database sono le seguenti:
1)Scaricare il registro dalla sezione release ,l'ultima versione
2)Upload di tutto il contenuto si filezilla
3)Sistemazione del file env secondo i dati dell'istituto
3)Ricerca sul browser del proprio registro elettronico per collegarsi ,esempio ilmioistituto.altervista.org/public
ma non esce niente , ossia è come se la pagina fosse inesistente ,come possiamo fare?Sbagliamo in qualche procedura?

@lucaccc

**Comment by sempliciniluigi89** [comment]
Necessiterei di una risposta urgente .

**Comment by trinko** [comment]
>Le procedure da me effettuate sul suo database sono le seguenti: 
>1)Scaricare il registro dalla sezione release ,l'ultima versione 
>2)Upload di tutto il contenuto si filezilla 
>3)Sistemazione del file env secondo i dati dell'istituto 
>3)Ricerca sul browser del proprio registro elettronico per collegarsi ,esempio ilmioistituto.altervista.org/public 
 
Manca il caricamento del database. I comandi da eseguire sono nel file **database.sql** e contengono (nella release 1.4.1) un database popolato con dati di test (classi, alunni, ecc.). 
Eventualmente si possono modificare o cancellare i dati presenti nelle istruzioni **INSERT**.

**Comment by sempliciniluigi89** [comment]
Buonasera,con l'autorizzazione del mio ex.collega ,se le mandassi le
credenziali del database sarebbe così gentile da eseguire solo i comandi
necessari nel file database.sql?Sarebbe bello vedere che sempre più scuole
adottano questo registro (poco conosciuto) nelle loro scuole

Il giorno lun 6 dic 2021 alle ore 17:32 Antonello Dessì <
***@***.***> ha scritto:

**Comment by trinko** [comment]
> Buonasera,con l'autorizzazione del mio ex.collega ,se le mandassi le credenziali del database sarebbe così gentile da eseguire solo i comandi necessari nel file database.sql?Sarebbe bello vedere che sempre più scuole adottano questo registro (poco conosciuto) nelle loro scuole

No, mi spiace, ma questo non è un servizio di assistenza.
Inoltre, poiché, come più volte detto, questo registro è stato progettato per rispondere alle esigenze di una particolare scuola, non di qualsiasi istituto scolastico, se non si hanno adeguate competenze informatiche non è assolutamente opportuno utilizzarlo, perché è probabile che ci si troverà in difficoltà in seguito, non sapendo come modificare le procedure (penso in particolare alla gestione degli scrutini).

**Comment by sempliciniluigi89** [comment]
Buonasera ,grazie mille per la risposta.Vorrà dire che l'istituto del mio ex.collega dovrà dire no al grande desiderio di adottare questo registro nel proprio istituto alquanto completo. Aggiungerei solo che nelle release non compare nessun rilascio aggiornato (per cui il problema legato agli scrutini ribadito più volte è rimasto invariato )ma il tutto avviene nella versione semplificata
