### ISSUE TITLE
OTTIMIZZAZIONE PER ALTERVISTA

### ISSUE THREAD

**Issue by manuelbarberi** [trinko/giuaschool#45]
Salve, secondo me sarebbe opportuno rendere giuaschool accessibile anche per altervista: ogni volta che inserisco admin come username e password non mi fa accedere .
Grazie

**Comment by alessiorossetti** [comment]
@manuelbarberi 

Buonasera, dal momento che anche io uso Altervista e vorrei tanto scaricare il registro Giuaschool per il mio istituto ,le vorrei chiedere se sarebbe disposto nell'aiutarmi in questa fase di installazione .Le lascio qui il mio indirizzo mail in modo da contattarmi privatamente , mi farebbe un gran favore ,anzi ,farebbe un'opera immensa per tutto il corpo docente del mio istituto. Grazie mille in anticipo 

alessiorossetti30@gmail.com

**Comment by scuolagioco** [comment]
> Salve, secondo me sarebbe opportuno rendere giuaschool accessibile anche per altervista: ogni volta che inserisco admin come username e password non mi fa accedere .
> Grazie

Salve, sarebbe disposto ad aiutarmi a installare il registro su Altervista per la mia scuola? Ho provato, ma niente! Mi faccia sapere, per favore. Buona serata

**Comment by manuelbarberi** [comment]
Guardate, anche io ho difficoltà; l'installazione in sè funziona ma non appena vado a inserire le credenziali non riesco ad accedere

**Comment by trinko** [comment]
Utilizza la nuova versione con la procedura di installazione.
