### ISSUE TITLE
GRANDE PROBLEMA

### ISSUE THREAD

**Issue by Lucaccc** [trinko/giuaschool#46]
Ho fatto l'aggiornamento del registro con l'ultima release (versione semplificata) e adesso non mi fa più accedere al registro elettronico...segnalandomi un'errore strano....
Cosa faccio?

**Comment by trinko** [comment]
Se hai aggiornato utilizzando le ultime modifiche (ultima _build_), devi fare anche l'aggiornamento del database, eseguendo i comandi che trovi nel file  **UPDATE-DATABSE-build.sql**. Questi comandi non cancellano i dati esistenti, ma aggiornano la struttura del database per rendere utilizzabili le ultime modifiche presenti.

**Comment by sempliciniluigi89** [comment]
Gentile @Lucaccc  , dal momento che lei è riuscito a scaricare ed avviare il registro elettronico per il suo istituto usando come me Altervista ,mi potrebbe aiutare per la stessa cosa ?Non le chiedo molto , dunque le lascio qui il mio contatto mail in modo da sentirci in privato
sempliciniluigi89@gmail.com
