### ISSUE TITLE
Stampe

### ISSUE THREAD

**Issue by rodolfo024** [trinko/giuaschool#47]
Volevo sapere in quali files andare oer cambiare l'intestazione della scuola ed il comune. Volevo inoltre far presente che il tabellone dei voti generato a fine scrutinio è scombinato. Grazie.

**Comment by trinko** [comment]
Il file con l'intestazione è l'immagine presente nel file: **public/img/intestazione-documenti.jpg**

Va sostituita con un'immagene JPEG di dimensioni 1000x216.

**Comment by rodolfo024** [comment]
Ok grazie. Per modificare invece i documenti che il registro genera esempio la comunicazione password, i verbali dello scrutinio ecc, su quali file devo agire? Grazie.

**Comment by trinko** [comment]
Le intestazioni dei documenti le ho recentemente uniformate in modo che facciano tutte riferimento all'immagine di intestazione.

Per modificare i contenuti, devi guardare i file nelle cartelle:

- **templates/pdf**: credenziali e altri documenti (voti, assenze, ecc.)
- **templates/email**: testo per invio via mail delle credenziali
- **templates/coordinatore/documenti** : documenti dello scrutinio

Tieni presente che il quadro dei voti dello scrutinio è purtroppo ancora generato direttamente dal codice PHP, nel file **src/Util/PagelleUtil.php**. Se vuoi modificare il testo devi guardare le varie funzioni **_CreaRiepilogoVoti_**

**Comment by rodolfo024** [comment]
Ciao, ho risolto il "problema" dei dati. Adesso c'è un altro problema, ovvero la pubblicazione. Facendo un test con account genitore scopro che viene fatto un "reindirizzamento" a public/genitori/pagelle, con un chiaro error404. Come posso sistemarlo?

**Comment by trinko** [comment]
E' strano, perché il messaggio di errore appare se non trova almeno uno scrutinio della classe chiuso e visibile (con data precedente a quella attuale).
Puoi provare a installare l'ultimo aggiornamento con cui si inserisce la gestione scrutini nel menu SCUOLA (con accesso amministratore).

[build#205 ](https://github.com/trinko/giuaschool/suites/4685493023/artifacts/127698552)

**Comment by rodolfo024** [comment]
Ciao, ho fatto l'aggiornamento ed anche del database. La versione indicata è sempre la 1.4.0 e compare anche il bottone scrutini dal lato admin. Da lato genitore compare adesso "dati non disponibili". Il problema è che quando si clicca su scrutini da admin compare l'errore 500.

**Comment by trinko** [comment]
E' probabile che ci siano inseriti in precedenza nella tabella **gs_definizione_scrutinio** che non corrispondono a quelli attesi.
Devi vedere il log per capire l'errore: **var/log/app_prod_...**

**Comment by rodolfo024** [comment]
ecco cosa c'è nel log

[2021-12-18 12:28:53] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Types\ConversionException: "Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 86 of 182 bytes'" at /home/jheiddkl/domains/giuaschool.x10host.com/public_html/vendor/doctrine/dbal/src/Types/ConversionException.php line 115 {"exception":"[object] (Doctrine\\DBAL\\Types\\ConversionException(code: 0): Could not convert database value to 'array' as an error was triggered by the unserialization: 'unserialize(): Error at offset 86 of 182 bytes' at /home/jheiddkl/domains/giuaschool.x10host.com/public_html/vendor/doctrine/dbal/src/Types/ConversionException.php:115)"} {"client_ip":"2.39.167.108","uri":"http://giuaschool.x10host.com/public/coordinatore/scrutinio","query_string":null,"method":"GET","username":"dirigente","roles":["ROLE_PRESIDE","ROLE_STAFF","ROLE_DOCENTE","ROLE_UTENTE"]}

sembra abbia problemi con il db

**Comment by trinko** [comment]
Sembra che ci siano dati invalidi nelle tabelle dello scrutinio. 
Se non è un problema, è meglio cancellare tutti i dati degli scrutini con i seguenti comandi sul database:
```
DELETE FROM gs_esito;
DELETE FROM gs_voto_scrutinio;
DELETE FROM gs_scrutinio;
DELETE FROM gs_definizione_consiglio;
```

Dopo aver ripulito tutto, dovresti reimpostare gli scrutini dal menu SCUOLA->SCRUTINI come amministratore e poi provare a completare nuovamente uno scrutinio.
