### ISSUE TITLE
Compresenza

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#55]
Buonasera ,dal momento che il mio è un liceo linguistico che come tutti i licei linguistici prevede una volta alla settimana la compresenza col madrelingua  nella stessa ora ,sarebbe possibile far modo di mettere una compresenza nella stessa ora in modo da far firmare tutte e due i docenti senza spostarsi per forza in un'altra ora occupando quella del collega?Grazie

**Comment by Lucaccc** [comment]
> Buonasera ,dal momento che il mio è un liceo linguistico che come tutti i licei linguistici prevede una volta alla settimana la compresenza col madrelingua nella stessa ora ,sarebbe possibile far modo di mettere una compresenza nella stessa ora in modo da far firmare tutte e due i docenti senza spostarsi per forza in un'altra ora occupando quella del collega?Grazie

Si può già fare. 
Basta assegnare la stessa cattedra a più docenti, e assegnare a uno di questi la compresenza (tra i tipi di insegnamento).
Ora il docente potrà firmare alla stessa ora e appariranno entrambi i nomi dei docenti

**Comment by trinko** [comment]
La cattedra può essere NORMALE, ITP o POTENZIAMENTO (che si possonono usare per la compresenza), ATTIVITA' ALTERNATIVA (si usa solo per la scelta della materia alternativa per la materia religione). 
SUPPLENZA non è una tipologia di cattedra, ma serve per indicare se è una cattedra di supplenza.

Quindi nel tuo caso puoi impostare ITP o POTENZIAMENTO: la differenza è che la cattedra di POTENZIAMENTO non partecipa agli scrutini. Per il resto non fa differenza.

Il comportamento del registro per gli argomenti è quello voluto: essendo in compresenza, l'argomento è condiviso con l'altro docente. Solitamente, l'argomento svolto nell'ora è unico per entrambi, solo che viene svolto  un lavoro differente dai docenti. In questo caso possono aggiungere qualche informazione in più.
