### ISSUE TITLE
Media materie assente portale genitori/alunni

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#56]
Buongiorno,nel mio istituto dal momento che non esiste un app per il registro giuaschool , numerosi genitori si lamentano del fatto che non possono vedere né la media generale né per singola materia come tutti i registri .Si potrebbe fare qualcosa?

**Comment by trinko** [comment]
E' prevista l'aggiunta di queste informazioni per i genitori, ma non posso pronunciarmi sui tempi di realizzazione.

Nel frattempo, però, segnalo l'esistenza di una nuova app per questo registro che ha anche questa funzionalità. L'app non è stata ancora ufficializzata perché non ho avuto modo di controllarla dal punto di vista della sicurezza (è stata realizzata da alcuni nostri studenti), ma è già utlizzabile:
[giua-app](https://giua-app.github.io/)

**Comment by sempliciniluigi89** [comment]
Ho dato un'occhiata alla pagina in cui è riportata la nuova app e devo ammettere che è fatta veramente bene come pochi.L'unico problema è che non so attivare l'ingresso con account google per gli studenti ,dal momento che non riesco proprio a capire il procedimento in cui consiste tutta l'attivazione del client_id.Se ci fosse qualcuno disponibile nell'aiutarmi in questo , sarei veramente grato.
