### ISSUE TITLE
ASSENZE

### ISSUE THREAD

**Issue by Lucaccc** [trinko/giuaschool#57]
Salve, @trinko o chi per lui, saprebbe dirmi perchè riesco a gestire le assenze solo nelle singole ore?
Se imposto l'altra modalità, con l'appello, mi compare un errore..
“ Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.”
Perchè?

**Comment by trinko** [comment]
La modalità a ore singole è stata pensata per quando l'intero istituto è in DAD (come lo scorso anno) e quindi è più agevole prendere le presenze ogni ora. 

La modalità delle assenze giornaliere è quella normale, e dovrebbe funzionare senza problemi. Per sapere il problema, devi leggere il file di log, dove vengono registrati gli errori: **var/log/app_prod...**
