### ISSUE TITLE
TESTATA SPARITA IN OGNI DOCUMENTO

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#58]
Buogiorno ,vorrei riportarvi il seguente problema:non è più presente in nessun documento la testata della scuola ,ossia risulta solo la scritta anno scolastico 2021/2022.Il che è preoccupante in quanto sia i verbali che altri documenti non possono avere atto ufficiale se provvisti di testata.

**Comment by trinko** [comment]
L'intestazione viene letta da una immagine: quindi il registro probabilmente non la trova.
Controlla:
- il template del documento, ad es. **templates/coordinatore/documenti/intestazione.html.twig** per le intestazioni dei documenti dello scrutinio
- l'immagine **public/img/intestazione-documenti.jpg**

Ovviamente se i template sono stati modificati, devi assicurarti che all'inizio abbiano il riferimento all'immagine.
