### ISSUE TITLE
ALUNNI SCOMPARSI PROBLEMA GRAVE 

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#60]
Buongiorno, avrei bisogno di una mano ,il problema è alquanto grave ed urgente: non so per quale motivo ma quando accedo come admin ed inserisco l'anagrafica di un alunno e clicco su conferma mi esce il messaggio che dice che tutto è avvenuto con successo , ma poi non mi ritrovo l'alunno nell'elenco delle anagrafi , è come se ci fosse realmente (perché di fatto se io riporto il nome utente nelle alias riesco ad accedere) ma non visibile nella tabella admin alunni sezione modifica.Mentre per i docenti e altro personale non si verifica questo problema.Come posso fare?E' urgente.

**Comment by trinko** [comment]
La cosa più probabile è che tu abbia modificato lo standard usato per le username di alunni e genitori, per cui non riesce ad associarli.
Gli alunni sono indicati come  **qualcosa.sX**, dove X è una cifra.
I genitori sono indicati con la stessa username che termina per **.fX** (primo genitore) e **.gX**  (secondo genitore)

Il problema che descrivi dovrebbe essere dovuto al solo cambio del formato della username per i genitori, quella degli alunni non dovrebbe essere rilevante.

**Comment by sempliciniluigi89** [comment]
Le posso fornire le credenziali del database in modo da vedere e sistemare l'errore dal momento che non ci riesco?

**Comment by sempliciniluigi89** [comment]
Mi contatti pure privatamente sulla mail :sempliciniluigi89@gmail.com

**Comment by sempliciniluigi89** [comment]
Mi può fornire il suo indirizzo mail in modo da contattarla privatamente?
