### ISSUE TITLE
Pubblicazione nel catalogo del software di Developers Italia

### ISSUE THREAD

**Issue by ruphy** [trinko/giuaschool#63]
Buongiorno,

girovagando per la rete ho trovato questo repository che mi sembra una ottima soluzione che sarebbe utile diffondere! Vi chiederei di valutare l'inclusione nel catalogo del riuso di developers.italia.it in modo che sia più conosciuto da altre scuole, attirando nuovi contributi e nuovi utenti, nel pieno spirito del codice dell'amministrazione digitale.

Il processo tecnico, molto minimale, è dettagliato qui: https://developers.italia.it/it/riuso/pubblicazione

In sostanza si tratta di aggiungere un file publiccode.yml al repository per descrivere la soluzione (la cui ultima specifica è disponibile su https://yml.publiccode.tools) e creare una Pull Request qui: https://github.com/italia/developers-italia-backend/blob/master/crawler/whitelist/thirdparty.yml .
Vi suggerisco caldamente di usare il comodo editor disponibile su https://publiccode-editor.developers.italia.it/,

Questo processo si può fare sia come semplici cittadini che direttamente come scuola, in questo caso certificando i propri repository attraverso questo link: https://onboarding.developers.italia.it/

Seguo questa issue e rimango a disposizione per chiarire eventuali dubbi e domande!

**Comment by trinko** [comment]
Grazie per la segnalazione. Penso di inserirlo a breve.
