### ISSUE TITLE
Risultato dopo aver sovraccaricato testata personalizzata

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#64]
Gentile Antonello Dessì , le comunico che ho caricato la testata così come da lei consigliato , ma il problema rimane invariato ,ossia non compare in nessun documento , il che è preoccupante

**Comment by trinko** [comment]
Dopo aver fatto modifiche di questo tipo è sempre necessario svuotare la cache:
- cancella tutti i file presenti nella cartella **var/cache/prod**
