### ISSUE TITLE
AGGIUNTA TIPOLOGIA GRAFICA DI VALUTAZIONE

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#66]
Buongiorno,sarebbe possibile affiancare alle tipologie di valutazione scritta,orale , pratica anche quella grafica dal momento che in molte scuole si svolge come materia arte e immagine  o comunque disegno tecnico ?

**Comment by trinko** [comment]
Esiste già la tipologia PRATICA che si usa normalmente anche per le prove grafiche. 
Diciamo che è da intendersi come PRATICA/GRAFICA.
