### ISSUE TITLE
CREAZIONE UTENTE AUTOMATICO-VELOCIZZAZIONE IMPORTAZIONI CSV 

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#67]
Buonasera ,sarebbe possibile creare in automatico il nome utente non appena si inserisce il nome e cognome dell'utente?Questo farebbe risparmiare molto tempo alle segreterie ,ed inoltre nell'importazione CSV degli alunni/docenti si potrebbe limitare solo ad un totale di celle es. solo "nome,cognome,codice fiscale,data di nascita e sesso? (Come LAMPSCHOOL) Lo chiedo perché trovo che compilare cella excel per cella anche escludendo i campi non obbligatori sia una missione  che richiede troppo tempo

**Comment by trinko** [comment]
Si può già fare, basta importare gli utenti con i file CSV e riempire solo i **campi obbligatori**.
Nella pagina delle importazioni da file sono indicati quali campi sono obbligatori.

**Comment by sempliciniluigi89** [comment]
Si lo so,ma anche questi obbligatori risultano essere numerosi,io mi
soffermerei a rendere obbligatorio solo nome,cognome,c.fiscale,data di
nascita esesso.Il resto come cattedra,corso etc può essere benissimamente
gestito all'interno dell'area admin



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
27/12/21,
09:53:53

Il giorno lun 27 dic 2021 alle ore 09:51 Antonello Dessì <
***@***.***> ha scritto:
