### ISSUE TITLE
COLORAZIONE ROSSO ALUNNI ASSENTI SEZIONE VOTI

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#68]
Buonasera ,dal momento che molti docenti si lamentano di sbagliare mettendo voti agli alunni assenti ,sarebbe possibile colorare quest'ultimi di rosso nella sezione voti in modo da capire che sono assenti e saltare a mettere la valutazione all'alunno  successivo ?

**Comment by trinko** [comment]
Nella nuova versione, in uscita a breve, viene segnalato con un avviso se si inserisce un voto ad un alunno assente.
