### ISSUE TITLE
aggiornamento

### ISSUE THREAD

**Issue by Lucaccc** [trinko/giuaschool#69]
Buongiorno, una domanda: gli ultimi aggiornamenti sono necessari? Cosa vanno a modificare (mi riferisco da quello "fix installazione" fino all'ultimo).

**Comment by trinko** [comment]
Sono state aggiunte alcune funzionalità e corretti dei bug minori. Ma aspetta l'uscita della prossima versione, sto ultimando un installer per semplificare le cose.

**Comment by sempliciniluigi89** [comment]
Funzionalità di che tipo?
