### ISSUE TITLE
GIUSTIFICA USCITA ANTICIPATA

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#70]
Buongiorno ,ci siamo resi conto che non è possibile incaricare ogni volta la preside nell'autorizzazione di numerose uscite che vengono effettuate al giorno, quindi sarebbe bello che anche l'uscita come il ritardo e l'assenza venisse giustificata .
P.S negli altri registri provati precedentemente era possibile mettere anche il fuori-classe quando un alunno era impegnato in un progetto scolastico

**Comment by trinko** [comment]
Si può fare già. 
Ogni docente può inserire l'uscita anticipata di un alunno e ha a disposizione una casella di testo dove inserire le motivazioni, ovvero la giustificazione.
Il fuori-classe non è per ora gestito.
