### ISSUE TITLE
Aggiornamento database

### ISSUE THREAD

**Issue by rodolfo024** [trinko/giuaschool#78]
Ciao, potresti darmi un file updatedatabase.sql come nella versione precedente per aggiornare il database in quanto quando dopo aver riscritto le cartelle (svuotato il server e reinseriti i nuovi file, ma con database "vecchio") compare l'errore 500. Questo accade anche con il db di prova fornito con il programma. I file che prelevo naturalmente sono i release e non i master.

**Comment by trinko** [comment]
Usa la nuova procedura di installazione della nuova versione. A breve disponibile
