### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by sempliciniluigi89** [trinko/giuaschool#84]
Buonasera, sarebbe possibile implementare un tempo limitato dopodiché  far uscire automaticamente l'utente dal portale?Mi sono accorto che resta sempre collegato fino a quando non si esce volontariamente

**Comment by trinko** [comment]
Il tempo massimo del collegamento non è gestito dall'applicazione, ma dipende dalla durata della sessione che viene impostata sul server web o sulle impostazioni del PHP (sempre sul server).
Se il tuo servizio di hosting te lo permette, puoi cambiare queste impostazioni.
